In [3]:
import pandas as pd

In [7]:
fortune = pd.read_csv("Datasets/fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head(4)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000

In [15]:
sectors.get_group("Apparel")["Profits"].sum()

np.int64(8236)

In [17]:
sectors.sum()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,BoeingUnited TechnologiesLockheed MartinGenera...,Aerospace and DefenseAerospace and DefenseAero...,"Chicago, ILFarmington, CTBethesda, MDFalls Chu...",357940,28742,968057
Apparel,NikeVFPVHRalph LaurenHanesbrandsLevi StraussCo...,ApparelApparelApparelApparelApparelApparelAppa...,"Beaverton, ORGreensboro, NCNew York, NYNew Yor...",95968,8236,346397
Business Services,ManpowerGroupOmnicom GroupAramarkVisaWaste Man...,"Temporary HelpAdvertising, marketingDiversifie...","Milwaukee, WINew York, NYPhiladelphia, PAFoste...",272195,28227,1361050
Chemicals,Dow ChemicalDuPontPPG IndustriesMonsantoEcolab...,ChemicalsChemicalsChemicalsChemicalsChemicalsC...,"Midland, MIWilmington, DEPittsburgh, PASt. Lou...",243897,22628,463651
Energy,Exxon MobilChevronPhillips 66Valero EnergyMara...,Petroleum RefiningPetroleum RefiningPetroleum ...,"Irving, TXSan Ramon, CAHouston, TXSan Antonio,...",1517809,-73447,1188927
Engineering & Construction,FluorAECOMJacobs Engineering GroupD.R. HortonL...,"Engineering, ConstructionEngineering, Construc...","Irving, TXLos Angeles, CAPasadena, CAFort Wort...",153983,5304,406708
Financials,Berkshire HathawayFannie MaeJ.P. Morgan ChaseB...,Insurance: Property and Casualty (Stock)Divers...,"Omaha, NEWashington, DCNew York, NYCharlotte, ...",2217159,260209,3359948
Food and Drug Stores,CVS HealthKrogerWalgreens Boots AlliancePublix...,Food and Drug StoresFood and Drug StoresFood a...,"Woonsocket, RICincinnati, OHDeerfield, ILLakel...",483769,16759,1395398
"Food, Beverages & Tobacco",Archer Daniels MidlandPepsiCoCoca-ColaTyson Fo...,Food ProductionFood Consumer ProductsBeverages...,"Chicago, ILPurchase, NYAtlanta, GASpringdale, ...",555967,51417,1211632
Health Care,McKessonUnitedHealth GroupAmerisourceBergenCar...,Wholesalers: Health CareHealth Care: Insurance...,"San Francisco, CAMinnetonka, MNChesterbrook, P...",1614707,106114,2678289
"Hotels, Resturants & Leisure",McDonald’sStarbucksMarriott InternationalYum B...,"Food ServicesFood ServicesHotels, Casinos, Res...","Oak Brook, ILSeattle, WABethesda, MDLouisville...",169546,20697,2484245
Household Products,Procter & GambleKimberly-ClarkColgate-Palmoliv...,Household and Personal ProductsHousehold and P...,"Cincinnati, OHIrving, TXNew York, NYNew Britai...",234737,14428,646038
Industrials,General ElectricCaterpillarHoneywell Internati...,Industrial MachineryConstruction and Farm Mach...,"Fairfield, CTPeoria, ILMorris Plains, NJSt. Pa...",497581,20764,1545229
Materials,AlcoaInternational PaperNucorUnited States Ste...,"MetalsPackaging, ContainersMetalsMetalsPackagi...","New York, NYMemphis, TNCharlotte, NCPittsburgh...",259145,4428,638123
Media,DisneyTwenty-First Century FoxTime WarnerCBSVi...,EntertainmentEntertainmentEntertainmentEnterta...,"Burbank, CANew York, NYNew York, NYNew York, N...",220764,24347,550314
Motor Vehicles & Parts,General MotorsFord MotorJohnson ControlsPaccar...,Motor Vehicles and PartsMotor Vehicles and Par...,"Detroit, MIDearborn, MIMilwaukee, WIBellevue, ...",482540,25898,1082560
Retailing,WalmartCostcoHome DepotTargetLowe’sBest BuyTJX...,General MerchandisersSpecialty Retailers: Othe...,"Bentonville, ARIssaquah, WAAtlanta, GAMinneapo...",1465076,47830,6227629
Technology,AppleAmazon.comHPMicrosoftIBMAlphabetIntelCisc...,"Computers, Office EquipmentInternet Services a...","Cupertino, CASeattle, WAPalo Alto, CARedmond, ...",1377600,180473,3578949
Telecommunications,AT&TVerizonComcastTime Warner CableCenturyLink...,TelecommunicationsTelecommunicationsTelecommun...,"Dallas, TXNew York, NYPhiladelphia, PANew York...",461834,48637,832468
Transportation,UPSFedExAmerican Airlines GroupDelta Air Lines...,"Mail, Package, and Freight DeliveryMail, Packa...","Atlanta, GAMemphis, TNFort Worth, TXAtlanta, G...",408508,44169,1536793
Wholesalers,SyscoIngram MicroWorld Fuel ServicesAvnetTech ...,Wholesalers: Food and GroceryWholesalers: Elec...,"Houston, TXIrvine, CAMiami, FLPhoenix, AZClear...",444800,8233,525597

In [21]:
sectors.min()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,B/E Aerospace,Aerospace and Defense,"Berwyn, PA",1923,-240,6955
Apparel,Carter’s,Apparel,"Atlanta, GA",2204,82,5978
Business Services,ABM Industries,"Advertising, marketing","Arlington, VA",1910,-1481,2400
Chemicals,A. Schulman,Chemicals,"Allentown, PA",2084,-816,1979
Energy,AES,Energy,"Akron, OH",1898,-23119,480
Engineering & Construction,AECOM,"Engineering, Construction","Atlanta, GA",1909,-155,1036
Financials,AIG,Commercial Banks,"Atlanta, GA",1902,-1194,187
Food and Drug Stores,CVS Health,Food and Drug Stores,"Austin, TX",2151,-62,1616
"Food, Beverages & Tobacco",Alliance One International,Beverages,"Arden Hills, MN",2066,-253,1857
Health Care,AbbVie,Health Care: Insurance and Managed Care,"Abbott Park, IL",1987,-458,2924
"Hotels, Resturants & Leisure",Bloomin’ Brands,Food Services,"Ann Arbor, MI",1896,-1394,8500
Household Products,Avon Products,"Home Equipment, Furnishings","Atlanta, GA",1914,-1149,4406
Industrials,3M,Construction and Farm Machinery,"Annapolis Junction, MD",1895,-6126,4104
Materials,A-Mark Precious Metals,"Building Materials, Glass","Atlanta, GA",1924,-1642,52
Media,AMC Networks,Entertainment,"Beverly Hills, CA",1921,-881,2341
Motor Vehicles & Parts,Allison Transmission Holdings,Motor Vehicles and Parts,"Akron, OH",1986,-889,2700
Retailing,99 Cents Only Stores,"Automotive Retailing, Services","Ankeny, IA",1999,-1243,2155
Technology,Activision Blizzard,Computer Peripherals,"Angleton, TX",1920,-4359,2285
Telecommunications,AT&T,Telecommunications,"Bethpage, NY",2726,-271,2700
Transportation,Alaska Air Group,Airlines,"Atlanta, GA",1995,-191,1223
Wholesalers,Airgas,Miscellaneous,"Atlanta, GA",1917,-502,500

In [23]:
sectors["Revenue"].mean()

Sector
Aerospace & Defense             17897.000000
Apparel                          6397.866667
Business Services                5337.156863
Chemicals                        8129.900000
Energy                          12441.057377
Engineering & Construction       5922.423077
Financials                      15950.784173
Food and Drug Stores            32251.266667
Food, Beverages & Tobacco       12929.465116
Health Care                     21529.426667
Hotels, Resturants & Leisure     6781.840000
Household Products               8383.464286
Industrials                     10816.978261
Materials                        6026.627907
Media                            8830.560000
Motor Vehicles & Parts          20105.833333
Retailing                       18313.450000
Technology                      13505.882353
Telecommunications              30788.933333
Transportation                  11347.444444
Wholesalers                     11120.000000
Name: Revenue, dtype: float64

In [27]:
sectors[["Revenue", "Profits"]].sum()

                              Revenue  Profits
Sector
Aerospace & Defense            357940    28742
Apparel                         95968     8236
Business Services              272195    28227
Chemicals                      243897    22628
Energy                        1517809   -73447
Engineering & Construction     153983     5304
Financials                    2217159   260209
Food and Drug Stores           483769    16759
Food, Beverages & Tobacco      555967    51417
Health Care                   1614707   106114
Hotels, Resturants & Leisure   169546    20697
Household Products             234737    14428
Industrials                    497581    20764
Materials                      259145     4428
Media                          220764    24347
Motor Vehicles & Parts         482540    25898
Retailing                     1465076    47830
Technology                    1377600   180473
Telecommunications             461834    48637
Transportation                 408508    44169
Wholesalers                    444800     8233

In [32]:
sectors["Employees"].mean()

Sector
Aerospace & Defense             48402.850000
Apparel                         23093.133333
Business Services               26687.254902
Chemicals                       15455.033333
Energy                           9745.303279
Engineering & Construction      15642.615385
Financials                      24172.287770
Food and Drug Stores            93026.533333
Food, Beverages & Tobacco       28177.488372
Health Care                     35710.520000
Hotels, Resturants & Leisure    99369.800000
Household Products              23072.785714
Industrials                     33591.934783
Materials                       14840.069767
Media                           22012.560000
Motor Vehicles & Parts          45106.666667
Retailing                       77845.362500
Technology                      35087.735294
Telecommunications              55497.866667
Transportation                  42688.694444
Wholesalers                     13139.925000
Name: Employees, dtype: float64

# Grouping by Multiple Columns

In [33]:
fortune = pd.read_csv("Datasets/fortune1000.csv", index_col="Rank")
sectors = fortune.groupby(["Sector", "Industry"])
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [38]:
sectors.size()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            20
Apparel              Apparel                                          15
Business Services    Advertising, marketing                            2
                     Diversified Outsourcing Services                 14
                     Education                                         3
                                                                      ..
Transportation       Trucking, Truck Leasing                           9
Wholesalers          Miscellaneous                                     1
                     Wholesalers: Diversified                         25
                     Wholesalers: Electronics and Office Equipment     8
                     Wholesalers: Food and Grocery                     6
Length: 79, dtype: int64

In [39]:
sectors["Employees"].mean()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            48402.850000
Apparel              Apparel                                          23093.133333
Business Services    Advertising, marketing                           62050.000000
                     Diversified Outsourcing Services                 50595.000000
                     Education                                        15585.000000
                                                                          ...
Transportation       Trucking, Truck Leasing                          18939.555556
Wholesalers          Miscellaneous                                     9200.000000
                     Wholesalers: Diversified                          9353.240000
                     Wholesalers: Electronics and Office Equipment    20832.625000
                     Wholesalers: Food and Grocery                    19317.500000
Name: Employees, Length: 79, dtype: float64

In [40]:
sectors["Revenue"].sum()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            357940
Apparel              Apparel                                           95968
Business Services    Advertising, marketing                            22748
                     Diversified Outsourcing Services                  64829
                     Education                                          7485
                                                                       ...
Transportation       Trucking, Truck Leasing                           35950
Wholesalers          Miscellaneous                                      8982
                     Wholesalers: Diversified                         176138
                     Wholesalers: Electronics and Office Equipment    147906
                     Wholesalers: Food and Grocery                    111774
Name: Revenue, Length: 79, dtype: int64

# The .add() Method