In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'2.3.3'

In [3]:
np.__version__

'2.2.6'

In [5]:
ice_cream=["Chocolate", "Vainilla", "Strawbrry", "Rum"]

In [7]:
pd.Series(ice_cream)

0    Chocolate
1     Vainilla
2    Strawbrry
3          Rum
dtype: object

In [11]:
lottery=[4,8,16,23,42]
pd.Series(lottery)

0     4
1     8
2    16
3    23
4    42
dtype: int64

In [10]:
registrations=[True, False, True, True]
pd.Series(registrations)

0     True
1    False
2     True
3     True
dtype: bool

In [13]:
webster = {"Perro": "an animal", "Bananas": "A delicious fruit"}

In [14]:
pd.Series(webster)

Perro              an animal
Bananas    A delicious fruit
dtype: object

# Intro to Methos

In [16]:
prices=[2.99, 23.5,78.9]

In [17]:
s= pd.Series(prices)

In [19]:
s.sum()

np.float64(105.39000000000001)

In [20]:
s.product()

np.float64(5543.9085000000005)

In [21]:
s.mean()

np.float64(35.13)

# Parameters and Arguments

In [22]:
fuits=["apple", "orange", "plum", "grape", "blueberry"]

In [23]:
weekdays= ["monday", "tuesday", "wednesday", "thursday", "friday"]

In [24]:
pd.Series(fuits,weekdays)

monday           apple
tuesday         orange
wednesday         plum
thursday         grape
friday       blueberry
dtype: object

In [26]:
pd.Series(data=fuits, index=weekdays)

monday           apple
tuesday         orange
wednesday         plum
thursday         grape
friday       blueberry
dtype: object

# Import Series with read_csv Method

In [27]:
pd.read_csv("DataSets/pokemon.csv")

        Pokemon     Type
0     Bulbasaur    Grass
1       Ivysaur    Grass
2      Venusaur    Grass
3    Charmander     Fire
4    Charmeleon     Fire
..          ...      ...
716     Yveltal     Dark
717     Zygarde   Dragon
718     Diancie     Rock
719       Hoopa  Psychic
720   Volcanion     Fire

[721 rows x 2 columns]

In [31]:
# Importar como serie 
pd.read_csv("DataSets/pokemon.csv", usecols=["Pokemon"]).squeeze(True)
# Importar como DataFrame
pd.read_csv("DataSets/pokemon.csv", usecols=["Pokemon"])

        Pokemon
0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
..          ...
716     Yveltal
717     Zygarde
718     Diancie
719       Hoopa
720   Volcanion

[721 rows x 1 columns]

In [3]:
pokemon = pd.read_csv("DataSets/pokemon.csv", usecols=["Pokemon"]).squeeze(True)

In [33]:
pd.read_csv("DataSets/google_stock_price.csv")

      Stock Price
0           50.12
1           54.10
2           54.65
3           52.38
4           52.95
...           ...
3007       772.88
3008       771.07
3009       773.18
3010       771.61
3011       782.22

[3012 rows x 1 columns]

In [40]:
pd.read_csv("DataSets/google_stock_price.csv", usecols=["Stock Price"]).squeeze(True)

0        50.12
1        54.10
2        54.65
3        52.38
4        52.95
         ...
3007    772.88
3008    771.07
3009    773.18
3010    771.61
3011    782.22
Name: Stock Price, Length: 3012, dtype: float64

In [2]:
google = pd.read_csv("DataSets/google_stock_price.csv", usecols=["Stock Price"]).squeeze(True)

# The .head() and .tail() Methods

In [38]:
pokemon.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Pokemon, dtype: object

In [42]:
google.tail(3)

3009    773.18
3010    771.61
3011    782.22
Name: Stock Price, dtype: float64

# Python built-in Fuctions

In [44]:
len(pokemon)

721

In [46]:
len(google)

3012

In [48]:
type(pokemon)

pandas.core.series.Series

In [50]:
dir(pokemon)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__bool__',
 '__class__',
 '__column_consortium_standard__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_binop',
 '_cacher',
 '_can_hold_na',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_expanddim',
 '_constructor_expanddim_from_mgr',
 '_constructor_from_mgr',
 '_data',
 '_deprecate_downcast',
 '_dir_additions',
 '_dir_deletions',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_duplicated',
 '_find_valid_index',
 '_flags',
 '_flex_method',
 '_from_mgr',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cacher',
 '_get_cleaned_column_resolvers',
 '_get_index_resolvers',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_rows_with_mask',
 '_get_value',
 '_get_values_tuple',
 '_get_with',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_init_dict',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_cached',
 '_is_copy',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_is_view_after_cow_rules',
 '_item_cache',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_map_values',
 '_maybe_update_cacher',
 '_memory_usage',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_name',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_protect_consolidate',
 '_reduce',
 '_references',
 '_reindex_axes',
 '_reindex_indexer',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_single',
 '_repr_data_resource_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_set_as_cached',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_labels',
 '_set_name',
 '_set_value',
 '_set_values',
 '_set_with',
 '_set_with_engine',
 '_shift_with_freq',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_take_with_is_copy',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'array',
 'asfreq',
 'asof',
 'astype',
 'at',
 'at_time',
 'attrs',
 'autocorr',
 'axes',
 'backfill',
 'between',
 'between_time',
 'bfill',
 'bool',
 'case_when',
 'clip',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtype',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'hasnans',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'interpolate',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'list',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'name',
 'nbytes',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'pipe',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'set_flags',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'str',
 'struct',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'view',
 'where',
 'xs']

In [51]:
sorted(pokemon)

['Abomasnow',
 'Abra',
 'Absol',
 'Accelgor',
 'Aegislash',
 'Aerodactyl',
 'Aggron',
 'Aipom',
 'Alakazam',
 'Alomomola',
 'Altaria',
 'Amaura',
 'Ambipom',
 'Amoonguss',
 'Ampharos',
 'Anorith',
 'Arbok',
 'Arcanine',
 'Arceus',
 'Archen',
 'Archeops',
 'Ariados',
 'Armaldo',
 'Aromatisse',
 'Aron',
 'Articuno',
 'Audino',
 'Aurorus',
 'Avalugg',
 'Axew',
 'Azelf',
 'Azumarill',
 'Azurill',
 'Bagon',
 'Baltoy',
 'Banette',
 'Barbaracle',
 'Barboach',
 'Basculin',
 'Bastiodon',
 'Bayleef',
 'Beartic',
 'Beautifly',
 'Beedrill',
 'Beheeyem',
 'Beldum',
 'Bellossom',
 'Bellsprout',
 'Bergmite',
 'Bibarel',
 'Bidoof',
 'Binacle',
 'Bisharp',
 'Blastoise',
 'Blaziken',
 'Blissey',
 'Blitzle',
 'Boldore',
 'Bonsly',
 'Bouffalant',
 'Braixen',
 'Braviary',
 'Breloom',
 'Bronzong',
 'Bronzor',
 'Budew',
 'Buizel',
 'Bulbasaur',
 'Buneary',
 'Bunnelby',
 'Burmy',
 'Butterfree',
 'Cacnea',
 'Cacturne',
 'Camerupt',
 'Carbink',
 'Carnivine',
 'Carracosta',
 'Carvanha',
 'Cascoon',
 'Castform',
 'Caterpie',
 'Celebi',
 'Chandelure',
 'Chansey',
 'Charizard',
 'Charmander',
 'Charmeleon',
 'Chatot',
 'Cherrim',
 'Cherubi',
 'Chesnaught',
 'Chespin',
 'Chikorita',
 'Chimchar',
 'Chimecho',
 'Chinchou',
 'Chingling',
 'Cinccino',
 'Clamperl',
 'Clauncher',
 'Clawitzer',
 'Claydol',
 'Clefable',
 'Clefairy',
 'Cleffa',
 'Cloyster',
 'Cobalion',
 'Cofagrigus',
 'Combee',
 'Combusken',
 'Conkeldurr',
 'Corphish',
 'Corsola',
 'Cottonee',
 'Cradily',
 'Cranidos',
 'Crawdaunt',
 'Cresselia',
 'Croagunk',
 'Crobat',
 'Croconaw',
 'Crustle',
 'Cryogonal',
 'Cubchoo',
 'Cubone',
 'Cyndaquil',
 'Darkrai',
 'Darmanitan',
 'Darumaka',
 'Dedenne',
 'Deerling',
 'Deino',
 'Delcatty',
 'Delibird',
 'Delphox',
 'Deoxys',
 'Dewgong',
 'Dewott',
 'Dialga',
 'Diancie',
 'Diggersby',
 'Diglett',
 'Ditto',
 'Dodrio',
 'Doduo',
 'Donphan',
 'Doublade',
 'Dragalge',
 'Dragonair',
 'Dragonite',
 'Drapion',
 'Dratini',
 'Drifblim',
 'Drifloon',
 'Drilbur',
 'Drowzee',
 'Druddigon',
 'Ducklett',
 'Dugtrio',
 'Dunsparce',
 'Duosion',
 'Durant',
 'Dusclops',
 'Dusknoir',
 'Duskull',
 'Dustox',
 'Dwebble',
 'Eelektrik',
 'Eelektross',
 'Eevee',
 'Ekans',
 'Electabuzz',
 'Electivire',
 'Electrike',
 'Electrode',
 'Elekid',
 'Elgyem',
 'Emboar',
 'Emolga',
 'Empoleon',
 'Entei',
 'Escavalier',
 'Espeon',
 'Espurr',
 'Excadrill',
 'Exeggcute',
 'Exeggutor',
 'Exploud',
 "Farfetch'd",
 'Fearow',
 'Feebas',
 'Fennekin',
 'Feraligatr',
 'Ferroseed',
 'Ferrothorn',
 'Finneon',
 'Flaaffy',
 'Flabébé',
 'Flareon',
 'Fletchinder',
 'Fletchling',
 'Floatzel',
 'Floette',
 'Florges',
 'Flygon',
 'Foongus',
 'Forretress',
 'Fraxure',
 'Frillish',
 'Froakie',
 'Frogadier',
 'Froslass',
 'Furfrou',
 'Furret',
 'Gabite',
 'Gallade',
 'Galvantula',
 'Garbodor',
 'Garchomp',
 'Gardevoir',
 'Gastly',
 'Gastrodon',
 'Genesect',
 'Gengar',
 'Geodude',
 'Gible',
 'Gigalith',
 'Girafarig',
 'Giratina',
 'Glaceon',
 'Glalie',
 'Glameow',
 'Gligar',
 'Gliscor',
 'Gloom',
 'Gogoat',
 'Golbat',
 'Goldeen',
 'Golduck',
 'Golem',
 'Golett',
 'Golurk',
 'Goodra',
 'Goomy',
 'Gorebyss',
 'Gothita',
 'Gothitelle',
 'Gothorita',
 'Gourgeist',
 'Granbull',
 'Graveler',
 'Greninja',
 'Grimer',
 'Grotle',
 'Groudon',
 'Grovyle',
 'Growlithe',
 'Grumpig',
 'Gulpin',
 'Gurdurr',
 'Gyarados',
 'Happiny',
 'Hariyama',
 'Haunter',
 'Hawlucha',
 'Haxorus',
 'Heatmor',
 'Heatran',
 'Heliolisk',
 'Helioptile',
 'Heracross',
 'Herdier',
 'Hippopotas',
 'Hippowdon',
 'Hitmonchan',
 'Hitmonlee',
 'Hitmontop',
 'Ho-oh',
 'Honchkrow',
 'Honedge',
 'Hoopa',
 'Hoothoot',
 'Hoppip',
 'Horsea',
 'Houndoom',
 'Houndour',
 'Huntail',
 'Hydreigon',
 'Hypno',
 'Igglybuff',
 'Illumise',
 'Infernape',
 'Inkay',
 'Ivysaur',
 'Jellicent',
 'Jigglypuff',
 'Jirachi',
 'Jolteon',
 'Joltik',
 'Jumpluff',
 'Jynx',
 'Kabuto',
 'Kabutops',
 'Kadabra',
 'Kakuna',
 'Kangaskhan',
 'Karrablast',
 'Kecleon',
 'Keldeo',
 'Kingdra',
 'Kingler',
 'Kirlia',
 'Klang',
 'Klefki',
 'Klink',
 'Klinklang',
 'Koffing',
 'Krabby',
 'Kricketot',
 'Kricketune',
 'Krokorok',
 'Krookodile',
 'Kyogre',
 'Kyurem',
 'Lairon',
 'Lampent',
 'Landorus',
 'Lanturn',
 'Lapras',
 'Larvesta',
 'Larvitar',
 'Latias',
 'Latios',
 'Leafeon',
 'Leavanny',
 'Ledian',
 'Ledyba',
 'Lickilicky',
 'Lickitung',
 'Liepard',
 'Lileep',
 'Lilligant',
 'Lillipup',
 'Linoone',
 'Litleo',
 'Litwick',
 'Lombre',
 'Lopunny',
 'Lotad',
 'Loudred',
 'Lucario',
 'Ludicolo',
 'Lugia',
 'Lumineon',
 'Lunatone',
 'Luvdisc',
 'Luxio',
 'Luxray',
 'Machamp',
 'Machoke',
 'Machop',
 'Magby',
 'Magcargo',
 'Magikarp',
 'Magmar',
 'Magmortar',
 'Magnemite',
 'Magneton',
 'Magnezone',
 'Makuhita',
 'Malamar',
 'Mamoswine',
 'Manaphy',
 'Mandibuzz',
 'Manectric',
 'Mankey',
 'Mantine',
 'Mantyke',
 'Maractus',
 'Mareep',
 'Marill',
 'Marowak',
 'Marshtomp',
 'Masquerain',
 'Mawile',
 'Medicham',
 'Meditite',
 'Meganium',
 'Meloetta',
 'Meowstic',
 'Meowth',
 'Mesprit',
 'Metagross',
 'Metang',
 'Metapod',
 'Mew',
 'Mewtwo',
 'Mienfoo',
 'Mienshao',
 'Mightyena',
 'Milotic',
 'Miltank',
 'Mime Jr.',
 'Minccino',
 'Minun',
 'Misdreavus',
 'Mismagius',
 'Moltres',
 'Monferno',
 'Mothim',
 'Mr. Mime',
 'Mudkip',
 'Muk',
 'Munchlax',
 'Munna',
 'Murkrow',
 'Musharna',
 'Natu',
 'Nidoking',
 'Nidoqueen',
 'Nidoran',
 'Nidoran♂',
 'Nidorina',
 'Nidorino',
 'Nincada',
 'Ninetales',
 'Ninjask',
 'Noctowl',
 'Noibat',
 'Noivern',
 'Nosepass',
 'Numel',
 'Nuzleaf',
 'Octillery',
 'Oddish',
 'Omanyte',
 'Omastar',
 'Onix',
 'Oshawott',
 'Pachirisu',
 'Palkia',
 'Palpitoad',
 'Pancham',
 'Pangoro',
 'Panpour',
 'Pansage',
 'Pansear',
 'Paras',
 'Parasect',
 'Patrat',
 'Pawniard',
 'Pelipper',
 'Persian',
 'Petilil',
 'Phanpy',
 'Phantump',
 'Phione',
 'Pichu',
 'Pidgeot',
 'Pidgeotto',
 'Pidgey',
 'Pidove',
 'Pignite',
 'Pikachu',
 'Piloswine',
 'Pineco',
 'Pinsir',
 'Piplup',
 'Plusle',
 'Politoed',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Ponyta',
 'Poochyena',
 'Porygon',
 'Porygon-Z',
 'Porygon2',
 'Primeape',
 'Prinplup',
 'Probopass',
 'Psyduck',
 'Pumpkaboo',
 'Pupitar',
 'Purrloin',
 'Purugly',
 'Pyroar',
 'Quagsire',
 'Quilava',
 'Quilladin',
 'Qwilfish',
 'Raichu',
 'Raikou',
 'Ralts',
 'Rampardos',
 'Rapidash',
 'Raticate',
 'Rattata',
 'Rayquaza',
 'Regice',
 'Regigigas',
 'Regirock',
 'Registeel',
 'Relicanth',
 'Remoraid',
 'Reshiram',
 'Reuniclus',
 'Rhydon',
 'Rhyhorn',
 'Rhyperior',
 'Riolu',
 'Roggenrola',
 'Roselia',
 'Roserade',
 'Rotom',
 'Rufflet',
 'Sableye',
 'Salamence',
 'Samurott',
 'Sandile',
 'Sandshrew',
 'Sandslash',
 'Sawk',
 'Sawsbuck',
 'Scatterbug',
 'Sceptile',
 'Scizor',
 'Scolipede',
 'Scrafty',
 'Scraggy',
 'Scyther',
 'Seadra',
 'Seaking',
 'Sealeo',
 'Seedot',
 'Seel',
 'Seismitoad',
 'Sentret',
 'Serperior',
 'Servine',
 'Seviper',
 'Sewaddle',
 'Sharpedo',
 'Shaymin',
 'Shedinja',
 'Shelgon',
 'Shellder',
 'Shellos',
 'Shelmet',
 'Shieldon',
 'Shiftry',
 'Shinx',
 'Shroomish',
 'Shuckle',
 'Shuppet',
 'Sigilyph',
 'Silcoon',
 'Simipour',
 'Simisage',
 'Simisear',
 'Skarmory',
 'Skiddo',
 'Skiploom',
 'Skitty',
 'Skorupi',
 'Skrelp',
 'Skuntank',
 'Slaking',
 'Slakoth',
 'Sliggoo',
 'Slowbro',
 'Slowking',
 'Slowpoke',
 'Slugma',
 'Slurpuff',
 'Smeargle',
 'Smoochum',
 'Sneasel',
 'Snivy',
 'Snorlax',
 'Snorunt',
 'Snover',
 'Snubbull',
 'Solosis',
 'Solrock',
 'Spearow',
 'Spewpa',
 'Spheal',
 'Spinarak',
 'Spinda',
 'Spiritomb',
 'Spoink',
 'Spritzee',
 'Squirtle',
 'Stantler',
 'Staraptor',
 'Staravia',
 'Starly',
 'Starmie',
 'Staryu',
 'Steelix',
 'Stoutland',
 'Stunfisk',
 'Stunky',
 'Sudowoodo',
 'Suicune',
 'Sunflora',
 'Sunkern',
 'Surskit',
 'Swablu',
 'Swadloon',
 'Swalot',
 'Swampert',
 'Swanna',
 'Swellow',
 'Swinub',
 'Swirlix',
 'Swoobat',
 'Sylveon',
 'Taillow',
 'Talonflame',
 'Tangela',
 'Tangrowth',
 'Tauros',
 'Teddiursa',
 'Tentacool',
 'Tentacruel',
 'Tepig',
 'Terrakion',
 'Throh',
 'Thundurus',
 'Timburr',
 'Tirtouga',
 'Togekiss',
 'Togepi',
 'Togetic',
 'Torchic',
 'Torkoal',
 'Tornadus',
 'Torterra',
 'Totodile',
 'Toxicroak',
 'Tranquill',
 'Trapinch',
 'Treecko',
 'Trevenant',
 'Tropius',
 'Trubbish',
 'Turtwig',
 'Tympole',
 'Tynamo',
 'Typhlosion',
 'Tyranitar',
 'Tyrantrum',
 'Tyrogue',
 'Tyrunt',
 'Umbreon',
 'Unfezant',
 'Unown',
 'Ursaring',
 'Uxie',
 'Vanillish',
 'Vanillite',
 'Vanilluxe',
 'Vaporeon',
 'Venipede',
 'Venomoth',
 'Venonat',
 'Venusaur',
 'Vespiquen',
 'Vibrava',
 'Victini',
 'Victreebel',
 'Vigoroth',
 'Vileplume',
 'Virizion',
 'Vivillon',
 'Volbeat',
 'Volcanion',
 'Volcarona',
 'Voltorb',
 'Vullaby',
 'Vulpix',
 'Wailmer',
 'Wailord',
 'Walrein',
 'Wartortle',
 'Watchog',
 'Weavile',
 'Weedle',
 'Weepinbell',
 'Weezing',
 'Whimsicott',
 'Whirlipede',
 'Whiscash',
 'Whismur',
 'Wigglytuff',
 'Wingull',
 'Wobbuffet',
 'Woobat',
 'Wooper',
 'Wormadam',
 'Wurmple',
 'Wynaut',
 'Xatu',
 'Xerneas',
 'Yamask',
 'Yanma',
 'Yanmega',
 'Yveltal',
 'Zangoose',
 'Zapdos',
 'Zebstrika',
 'Zekrom',
 'Zigzagoon',
 'Zoroark',
 'Zorua',
 'Zubat',
 'Zweilous',
 'Zygarde']

In [4]:
sorted(pokemon, reverse=True)

['Zygarde',
 'Zweilous',
 'Zubat',
 'Zorua',
 'Zoroark',
 'Zigzagoon',
 'Zekrom',
 'Zebstrika',
 'Zapdos',
 'Zangoose',
 'Yveltal',
 'Yanmega',
 'Yanma',
 'Yamask',
 'Xerneas',
 'Xatu',
 'Wynaut',
 'Wurmple',
 'Wormadam',
 'Wooper',
 'Woobat',
 'Wobbuffet',
 'Wingull',
 'Wigglytuff',
 'Whismur',
 'Whiscash',
 'Whirlipede',
 'Whimsicott',
 'Weezing',
 'Weepinbell',
 'Weedle',
 'Weavile',
 'Watchog',
 'Wartortle',
 'Walrein',
 'Wailord',
 'Wailmer',
 'Vulpix',
 'Vullaby',
 'Voltorb',
 'Volcarona',
 'Volcanion',
 'Volbeat',
 'Vivillon',
 'Virizion',
 'Vileplume',
 'Vigoroth',
 'Victreebel',
 'Victini',
 'Vibrava',
 'Vespiquen',
 'Venusaur',
 'Venonat',
 'Venomoth',
 'Venipede',
 'Vaporeon',
 'Vanilluxe',
 'Vanillite',
 'Vanillish',
 'Uxie',
 'Ursaring',
 'Unown',
 'Unfezant',
 'Umbreon',
 'Tyrunt',
 'Tyrogue',
 'Tyrantrum',
 'Tyranitar',
 'Typhlosion',
 'Tynamo',
 'Tympole',
 'Turtwig',
 'Trubbish',
 'Tropius',
 'Trevenant',
 'Treecko',
 'Trapinch',
 'Tranquill',
 'Toxicroak',
 'Totodile',
 'Torterra',
 'Tornadus',
 'Torkoal',
 'Torchic',
 'Togetic',
 'Togepi',
 'Togekiss',
 'Tirtouga',
 'Timburr',
 'Thundurus',
 'Throh',
 'Terrakion',
 'Tepig',
 'Tentacruel',
 'Tentacool',
 'Teddiursa',
 'Tauros',
 'Tangrowth',
 'Tangela',
 'Talonflame',
 'Taillow',
 'Sylveon',
 'Swoobat',
 'Swirlix',
 'Swinub',
 'Swellow',
 'Swanna',
 'Swampert',
 'Swalot',
 'Swadloon',
 'Swablu',
 'Surskit',
 'Sunkern',
 'Sunflora',
 'Suicune',
 'Sudowoodo',
 'Stunky',
 'Stunfisk',
 'Stoutland',
 'Steelix',
 'Staryu',
 'Starmie',
 'Starly',
 'Staravia',
 'Staraptor',
 'Stantler',
 'Squirtle',
 'Spritzee',
 'Spoink',
 'Spiritomb',
 'Spinda',
 'Spinarak',
 'Spheal',
 'Spewpa',
 'Spearow',
 'Solrock',
 'Solosis',
 'Snubbull',
 'Snover',
 'Snorunt',
 'Snorlax',
 'Snivy',
 'Sneasel',
 'Smoochum',
 'Smeargle',
 'Slurpuff',
 'Slugma',
 'Slowpoke',
 'Slowking',
 'Slowbro',
 'Sliggoo',
 'Slakoth',
 'Slaking',
 'Skuntank',
 'Skrelp',
 'Skorupi',
 'Skitty',
 'Skiploom',
 'Skiddo',
 'Skarmory',
 'Simisear',
 'Simisage',
 'Simipour',
 'Silcoon',
 'Sigilyph',
 'Shuppet',
 'Shuckle',
 'Shroomish',
 'Shinx',
 'Shiftry',
 'Shieldon',
 'Shelmet',
 'Shellos',
 'Shellder',
 'Shelgon',
 'Shedinja',
 'Shaymin',
 'Sharpedo',
 'Sewaddle',
 'Seviper',
 'Servine',
 'Serperior',
 'Sentret',
 'Seismitoad',
 'Seel',
 'Seedot',
 'Sealeo',
 'Seaking',
 'Seadra',
 'Scyther',
 'Scraggy',
 'Scrafty',
 'Scolipede',
 'Scizor',
 'Sceptile',
 'Scatterbug',
 'Sawsbuck',
 'Sawk',
 'Sandslash',
 'Sandshrew',
 'Sandile',
 'Samurott',
 'Salamence',
 'Sableye',
 'Rufflet',
 'Rotom',
 'Roserade',
 'Roselia',
 'Roggenrola',
 'Riolu',
 'Rhyperior',
 'Rhyhorn',
 'Rhydon',
 'Reuniclus',
 'Reshiram',
 'Remoraid',
 'Relicanth',
 'Registeel',
 'Regirock',
 'Regigigas',
 'Regice',
 'Rayquaza',
 'Rattata',
 'Raticate',
 'Rapidash',
 'Rampardos',
 'Ralts',
 'Raikou',
 'Raichu',
 'Qwilfish',
 'Quilladin',
 'Quilava',
 'Quagsire',
 'Pyroar',
 'Purugly',
 'Purrloin',
 'Pupitar',
 'Pumpkaboo',
 'Psyduck',
 'Probopass',
 'Prinplup',
 'Primeape',
 'Porygon2',
 'Porygon-Z',
 'Porygon',
 'Poochyena',
 'Ponyta',
 'Poliwrath',
 'Poliwhirl',
 'Poliwag',
 'Politoed',
 'Plusle',
 'Piplup',
 'Pinsir',
 'Pineco',
 'Piloswine',
 'Pikachu',
 'Pignite',
 'Pidove',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Pichu',
 'Phione',
 'Phantump',
 'Phanpy',
 'Petilil',
 'Persian',
 'Pelipper',
 'Pawniard',
 'Patrat',
 'Parasect',
 'Paras',
 'Pansear',
 'Pansage',
 'Panpour',
 'Pangoro',
 'Pancham',
 'Palpitoad',
 'Palkia',
 'Pachirisu',
 'Oshawott',
 'Onix',
 'Omastar',
 'Omanyte',
 'Oddish',
 'Octillery',
 'Nuzleaf',
 'Numel',
 'Nosepass',
 'Noivern',
 'Noibat',
 'Noctowl',
 'Ninjask',
 'Ninetales',
 'Nincada',
 'Nidorino',
 'Nidorina',
 'Nidoran♂',
 'Nidoran',
 'Nidoqueen',
 'Nidoking',
 'Natu',
 'Musharna',
 'Murkrow',
 'Munna',
 'Munchlax',
 'Muk',
 'Mudkip',
 'Mr. Mime',
 'Mothim',
 'Monferno',
 'Moltres',
 'Mismagius',
 'Misdreavus',
 'Minun',
 'Minccino',
 'Mime Jr.',
 'Miltank',
 'Milotic',
 'Mightyena',
 'Mienshao',
 'Mienfoo',
 'Mewtwo',
 'Mew',
 'Metapod',
 'Metang',
 'Metagross',
 'Mesprit',
 'Meowth',
 'Meowstic',
 'Meloetta',
 'Meganium',
 'Meditite',
 'Medicham',
 'Mawile',
 'Masquerain',
 'Marshtomp',
 'Marowak',
 'Marill',
 'Mareep',
 'Maractus',
 'Mantyke',
 'Mantine',
 'Mankey',
 'Manectric',
 'Mandibuzz',
 'Manaphy',
 'Mamoswine',
 'Malamar',
 'Makuhita',
 'Magnezone',
 'Magneton',
 'Magnemite',
 'Magmortar',
 'Magmar',
 'Magikarp',
 'Magcargo',
 'Magby',
 'Machop',
 'Machoke',
 'Machamp',
 'Luxray',
 'Luxio',
 'Luvdisc',
 'Lunatone',
 'Lumineon',
 'Lugia',
 'Ludicolo',
 'Lucario',
 'Loudred',
 'Lotad',
 'Lopunny',
 'Lombre',
 'Litwick',
 'Litleo',
 'Linoone',
 'Lillipup',
 'Lilligant',
 'Lileep',
 'Liepard',
 'Lickitung',
 'Lickilicky',
 'Ledyba',
 'Ledian',
 'Leavanny',
 'Leafeon',
 'Latios',
 'Latias',
 'Larvitar',
 'Larvesta',
 'Lapras',
 'Lanturn',
 'Landorus',
 'Lampent',
 'Lairon',
 'Kyurem',
 'Kyogre',
 'Krookodile',
 'Krokorok',
 'Kricketune',
 'Kricketot',
 'Krabby',
 'Koffing',
 'Klinklang',
 'Klink',
 'Klefki',
 'Klang',
 'Kirlia',
 'Kingler',
 'Kingdra',
 'Keldeo',
 'Kecleon',
 'Karrablast',
 'Kangaskhan',
 'Kakuna',
 'Kadabra',
 'Kabutops',
 'Kabuto',
 'Jynx',
 'Jumpluff',
 'Joltik',
 'Jolteon',
 'Jirachi',
 'Jigglypuff',
 'Jellicent',
 'Ivysaur',
 'Inkay',
 'Infernape',
 'Illumise',
 'Igglybuff',
 'Hypno',
 'Hydreigon',
 'Huntail',
 'Houndour',
 'Houndoom',
 'Horsea',
 'Hoppip',
 'Hoothoot',
 'Hoopa',
 'Honedge',
 'Honchkrow',
 'Ho-oh',
 'Hitmontop',
 'Hitmonlee',
 'Hitmonchan',
 'Hippowdon',
 'Hippopotas',
 'Herdier',
 'Heracross',
 'Helioptile',
 'Heliolisk',
 'Heatran',
 'Heatmor',
 'Haxorus',
 'Hawlucha',
 'Haunter',
 'Hariyama',
 'Happiny',
 'Gyarados',
 'Gurdurr',
 'Gulpin',
 'Grumpig',
 'Growlithe',
 'Grovyle',
 'Groudon',
 'Grotle',
 'Grimer',
 'Greninja',
 'Graveler',
 'Granbull',
 'Gourgeist',
 'Gothorita',
 'Gothitelle',
 'Gothita',
 'Gorebyss',
 'Goomy',
 'Goodra',
 'Golurk',
 'Golett',
 'Golem',
 'Golduck',
 'Goldeen',
 'Golbat',
 'Gogoat',
 'Gloom',
 'Gliscor',
 'Gligar',
 'Glameow',
 'Glalie',
 'Glaceon',
 'Giratina',
 'Girafarig',
 'Gigalith',
 'Gible',
 'Geodude',
 'Gengar',
 'Genesect',
 'Gastrodon',
 'Gastly',
 'Gardevoir',
 'Garchomp',
 'Garbodor',
 'Galvantula',
 'Gallade',
 'Gabite',
 'Furret',
 'Furfrou',
 'Froslass',
 'Frogadier',
 'Froakie',
 'Frillish',
 'Fraxure',
 'Forretress',
 'Foongus',
 'Flygon',
 'Florges',
 'Floette',
 'Floatzel',
 'Fletchling',
 'Fletchinder',
 'Flareon',
 'Flabébé',
 'Flaaffy',
 'Finneon',
 'Ferrothorn',
 'Ferroseed',
 'Feraligatr',
 'Fennekin',
 'Feebas',
 'Fearow',
 "Farfetch'd",
 'Exploud',
 'Exeggutor',
 'Exeggcute',
 'Excadrill',
 'Espurr',
 'Espeon',
 'Escavalier',
 'Entei',
 'Empoleon',
 'Emolga',
 'Emboar',
 'Elgyem',
 'Elekid',
 'Electrode',
 'Electrike',
 'Electivire',
 'Electabuzz',
 'Ekans',
 'Eevee',
 'Eelektross',
 'Eelektrik',
 'Dwebble',
 'Dustox',
 'Duskull',
 'Dusknoir',
 'Dusclops',
 'Durant',
 'Duosion',
 'Dunsparce',
 'Dugtrio',
 'Ducklett',
 'Druddigon',
 'Drowzee',
 'Drilbur',
 'Drifloon',
 'Drifblim',
 'Dratini',
 'Drapion',
 'Dragonite',
 'Dragonair',
 'Dragalge',
 'Doublade',
 'Donphan',
 'Doduo',
 'Dodrio',
 'Ditto',
 'Diglett',
 'Diggersby',
 'Diancie',
 'Dialga',
 'Dewott',
 'Dewgong',
 'Deoxys',
 'Delphox',
 'Delibird',
 'Delcatty',
 'Deino',
 'Deerling',
 'Dedenne',
 'Darumaka',
 'Darmanitan',
 'Darkrai',
 'Cyndaquil',
 'Cubone',
 'Cubchoo',
 'Cryogonal',
 'Crustle',
 'Croconaw',
 'Crobat',
 'Croagunk',
 'Cresselia',
 'Crawdaunt',
 'Cranidos',
 'Cradily',
 'Cottonee',
 'Corsola',
 'Corphish',
 'Conkeldurr',
 'Combusken',
 'Combee',
 'Cofagrigus',
 'Cobalion',
 'Cloyster',
 'Cleffa',
 'Clefairy',
 'Clefable',
 'Claydol',
 'Clawitzer',
 'Clauncher',
 'Clamperl',
 'Cinccino',
 'Chingling',
 'Chinchou',
 'Chimecho',
 'Chimchar',
 'Chikorita',
 'Chespin',
 'Chesnaught',
 'Cherubi',
 'Cherrim',
 'Chatot',
 'Charmeleon',
 'Charmander',
 'Charizard',
 'Chansey',
 'Chandelure',
 'Celebi',
 'Caterpie',
 'Castform',
 'Cascoon',
 'Carvanha',
 'Carracosta',
 'Carnivine',
 'Carbink',
 'Camerupt',
 'Cacturne',
 'Cacnea',
 'Butterfree',
 'Burmy',
 'Bunnelby',
 'Buneary',
 'Bulbasaur',
 'Buizel',
 'Budew',
 'Bronzor',
 'Bronzong',
 'Breloom',
 'Braviary',
 'Braixen',
 'Bouffalant',
 'Bonsly',
 'Boldore',
 'Blitzle',
 'Blissey',
 'Blaziken',
 'Blastoise',
 'Bisharp',
 'Binacle',
 'Bidoof',
 'Bibarel',
 'Bergmite',
 'Bellsprout',
 'Bellossom',
 'Beldum',
 'Beheeyem',
 'Beedrill',
 'Beautifly',
 'Beartic',
 'Bayleef',
 'Bastiodon',
 'Basculin',
 'Barboach',
 'Barbaracle',
 'Banette',
 'Baltoy',
 'Bagon',
 'Azurill',
 'Azumarill',
 'Azelf',
 'Axew',
 'Avalugg',
 'Aurorus',
 'Audino',
 'Articuno',
 'Aron',
 'Aromatisse',
 'Armaldo',
 'Ariados',
 'Archeops',
 'Archen',
 'Arceus',
 'Arcanine',
 'Arbok',
 'Anorith',
 'Ampharos',
 'Amoonguss',
 'Ambipom',
 'Amaura',
 'Altaria',
 'Alomomola',
 'Alakazam',
 'Aipom',
 'Aggron',
 'Aerodactyl',
 'Aegislash',
 'Accelgor',
 'Absol',
 'Abra',
 'Abomasnow']

In [5]:
sorted(google)

[49.95,
 50.07,
 50.12,
 50.7,
 50.74,
 50.95,
 51.1,
 51.1,
 51.13,
 52.38,
 52.61,
 52.95,
 53.02,
 53.7,
 53.9,
 54.1,
 54.65,
 55.69,
 55.94,
 56.93,
 58.69,
 58.86,
 59.07,
 59.13,
 59.62,
 59.86,
 60.35,
 63.37,
 64.74,
 65.47,
 66.22,
 67.46,
 67.56,
 68.47,
 68.63,
 68.8,
 69.12,
 69.36,
 70.17,
 70.38,
 70.93,
 71.98,
 73.9,
 74.51,
 74.62,
 82.47,
 83.68,
 83.69,
 83.85,
 84.27,
 84.59,
 84.62,
 84.91,
 85.14,
 85.63,
 85.74,
 86.13,
 86.16,
 86.19,
 86.19,
 86.63,
 87.29,
 87.41,
 87.71,
 88.06,
 88.15,
 88.47,
 88.81,
 89.21,
 89.22,
 89.26,
 89.4,
 89.54,
 89.56,
 89.61,
 89.61,
 89.7,
 89.8,
 89.89,
 89.9,
 89.93,
 89.93,
 89.95,
 90.11,
 90.13,
 90.16,
 90.27,
 90.35,
 90.43,
 90.58,
 90.62,
 90.81,
 90.9,
 90.91,
 91.42,
 91.78,
 92.26,
 92.34,
 92.41,
 92.42,
 92.5,
 92.51,
 92.55,
 92.84,
 92.86,
 92.89,
 92.94,
 93.06,
 93.39,
 93.41,
 93.61,
 93.61,
 93.86,
 93.9,
 93.9,
 93.95,
 94.05,
 94.18,
 94.19,
 94.31,
 94.35,
 94.52,
 94.53,
 95.07,
 95.22,
 95.59,
 95.6,
 95.63,
 95.69,
 95.74,
 95.85,
 95.86,
 95.93,
 96.28,
 96.3,
 96.35,
 96.37,
 96.4,
 96.52,
 96.55,
 96.66,
 96.67,
 96.78,
 96.83,
 96.86,
 96.88,
 96.88,
 97.15,
 97.34,
 97.43,
 97.52,
 97.57,
 97.59,
 97.71,
 97.92,
 97.92,
 98.55,
 98.7,
 98.85,
 98.88,
 98.95,
 99.11,
 99.22,
 99.89,
 101.25,
 101.85,
 102.01,
 102.08,
 102.88,
 105.32,
 107.8,
 109.27,
 109.62,
 109.78,
 109.89,
 111.03,
 111.65,
 112.9,
 112.98,
 113.38,
 113.79,
 113.9,
 114.14,
 114.25,
 114.51,
 115.41,
 115.53,
 116.45,
 119.46,
 119.47,
 120.68,
 127.6,
 127.87,
 128.59,
 129.47,
 129.65,
 130.27,
 131.08,
 132.86,
 132.87,
 136.87,
 137.03,
 137.26,
 137.42,
 138.5,
 138.58,
 139.04,
 139.58,
 139.64,
 139.65,
 139.86,
 139.86,
 139.95,
 139.99,
 140.0,
 140.88,
 141.11,
 141.14,
 141.15,
 141.23,
 141.23,
 141.65,
 141.85,
 141.86,
 141.88,
 142.41,
 142.68,
 142.7,
 142.86,
 142.98,
 143.01,
 143.21,
 143.41,
 143.49,
 143.74,
 143.78,
 143.81,
 143.86,
 144.08,
 144.08,
 144.51,
 144.71,
 144.72,
 145.3,
 145.32,
 145.35,
 145.48,
 145.48,
 145.62,
 145.64,
 145.66,
 145.75,
 145.9,
 146.03,
 146.21,
 146.33,
 146.41,
 146.53,
 146.6,
 146.93,
 147.29,
 147.55,
 147.62,
 147.71,
 147.78,
 147.9,
 147.92,
 147.97,
 148.32,
 148.41,
 148.48,
 148.5,
 148.56,
 148.56,
 148.57,
 148.72,
 148.86,
 149.28,
 149.35,
 149.4,
 149.45,
 149.62,
 149.69,
 149.91,
 149.95,
 149.96,
 150.03,
 150.29,
 150.33,
 150.33,
 150.44,
 150.85,
 150.9,
 151.05,
 151.16,
 151.32,
 151.35,
 151.39,
 151.4,
 151.45,
 151.49,
 151.74,
 151.9,
 152.35,
 152.67,
 152.83,
 152.85,
 152.9,
 153.1,
 153.67,
 153.8,
 153.93,
 154.13,
 154.2,
 154.26,
 154.66,
 154.72,
 154.8,
 154.85,
 154.93,
 154.98,
 155.17,
 155.18,
 155.2,
 155.34,
 155.53,
 155.57,
 155.68,
 155.79,
 155.84,
 155.88,
 156.19,
 156.22,
 156.34,
 156.81,
 156.81,
 156.98,
 157.0,
 157.38,
 157.46,
 157.52,
 157.72,
 158.07,
 158.8,
 159.18,
 159.23,
 159.3,
 159.69,
 160.5,
 160.84,
 161.6,
 161.77,
 162.05,
 162.19,
 162.43,
 162.48,
 162.58,
 163.42,
 163.86,
 164.33,
 164.58,
 164.81,
 164.86,
 164.91,
 165.4,
 165.44,
 165.57,
 165.83,
 166.38,
 166.86,
 167.5,
 168.36,
 168.42,
 168.58,
 168.83,
 168.89,
 169.1,
 169.22,
 169.42,
 169.48,
 169.73,
 169.78,
 169.79,
 169.94,
 170.05,
 170.11,
 170.65,
 170.77,
 170.95,
 171.02,
 171.15,
 171.16,
 171.17,
 171.33,
 171.33,
 171.49,
 171.49,
 171.86,
 172.08,
 172.55,
 172.68,
 172.83,
 173.05,
 173.07,
 173.28,
 173.41,
 173.68,
 173.86,
 173.92,
 174.13,
 174.15,
 174.16,
 175.4,
 175.98,
 176.33,
 176.35,
 176.38,
 176.47,
 176.68,
 176.76,
 176.87,
 177.54,
 177.66,
 178.66,
 178.82,
 178.84,
 178.91,
 179.08,
 179.15,
 179.21,
 179.5,
 179.67,
 180.82,
 181.07,
 181.12,
 181.13,
 181.17,
 181.19,
 181.34,
 182.04,
 182.22,
 182.56,
 182.72,
 183.05,
 183.11,
 183.29,
 183.43,
 183.78,
 183.87,
 183.94,
 184.07,
 184.19,
 184.19,
 184.27,
 184.36,
 184.53,
 184.66,
 184.71,
 184.82,
 185.29,
 185.31,
 185.42,
 185.45,
 185.46,
 185.72,
 185.78,
 185.88,
 186.06,
 186.08,
 186.44,
 186.53,
 186.68,
 186.74,
 186.88,
 186.91,
 187.03,
 187.06,
 187.51,
 187.57,
 187.6,
 187.91,
 188.04,
 188.28,
 188.41,
 188.46,
 188.51,
 188.74,
 188.79,
 188.85,
 188.87,
 188.9,
 188.96,
 189.06,
 189.08,
 189.11,
 189.2,
 189.29,
 189.39,
 189.46,
 189.47,
 189.5,
 189.53,
 189.56,
 189.65,
 189.88,
 190.18,
 190.28,
 190.29,
 190.31,
 190.31,
 190.32,
 190.43,
 190.48,
 190.54,
 190.58,
 190.59,
 191.01,
 191.12,
 191.3,
 191.49,
 191.66,
 191.74,
 191.85,
 191.99,
 192.0,
 192.15,
 192.36,
 192.56,
 192.71,
 192.78,
 192.78,
 193.06,
 193.07,
 193.09,
 193.11,
 193.26,
 193.31,
 193.37,
 193.39,
 193.56,
 193.67,
 193.87,
 193.88,
 194.03,
 194.18,
 194.49,
 194.55,
 194.58,
 194.66,
 194.76,
 194.8,
 194.8,
 194.8,
 194.86,
 194.99,
 195.0,
 195.02,
 195.05,
 195.15,
 195.25,
 195.3,
 195.35,
 195.54,
 195.75,
 195.92,
 196.2,
 196.45,
 196.55,
 196.65,
 196.89,
 196.95,
 197.18,
 197.19,
 197.2,
 197.29,
 197.32,
 197.79,
 197.82,
 198.05,
 198.11,
 198.12,
 198.22,
 198.29,
 198.3,
 198.39,
 198.88,
 199.24,
 199.25,
 199.3,
 199.31,
 199.53,
 199.78,
 199.9,
 200.06,
 200.52,
 200.69,
 200.75,
 200.79,
 200.86,
 200.88,
 200.96,
 201.04,
 201.26,
 201.29,
 201.29,
 201.32,
 201.52,
 201.53,
 201.55,
 201.57,
 201.59,
 201.69,
 201.7,
 201.79,
 201.79,
 201.82,
 201.91,
 201.91,
 201.92,
 201.97,
 201.98,
 202.07,
 202.23,
 202.25,
 202.58,
 202.64,
 202.72,
 202.85,
 202.88,
 203.08,
 203.21,
 203.22,
 203.23,
 203.46,
 203.47,
 203.74,
 203.79,
 203.79,
 204.04,
 204.2,
 204.21,
 204.27,
 204.4,
 204.44,
 204.48,
 204.6,
 204.63,
 204.74,
 204.99,
 204.99,
 205.04,
 205.12,
 205.38,
 205.65,
 205.7,
 206.1,
 206.6,
 206.82,
 206.84,
 206.87,
 206.99,
 207.04,
 207.14,
 207.22,
 207.29,
 207.37,
 207.64,
 207.68,
 207.79,
 207.98,
 208.03,
 208.18,
 208.41,
 208.42,
 208.54,
 208.64,
 208.7,
 208.76,
 208.89,
 209.12,
 209.27,
 209.29,
 209.44,
 209.46,
 209.73,
 209.76,
 209.8,
 209.83,
 209.86,
 210.01,
 210.04,
 210.11,
 210.52,
 210.58,
 210.66,
 211.05,
 211.22,
 211.38,
 211.39,
 211.53,
 211.86,
 211.94,
 212.07,
 212.09,
 212.11,
 212.13,
 212.21,
 212.45,
 212.77,
 212.82,
 212.95,
 213.04,
 213.07,
 213.11,
 213.13,
 213.2,
 213.37,
 213.44,
 213.51,
 213.54,
 213.63,
 213.74,
 213.99,
 214.1,
 214.29,
 214.29,
 214.42,
 214.66,
 214.85,
 214.86,
 214.87,
 214.91,
 215.25,
 215.3,
 215.61,
 215.78,
 215.8,
 216.08,
 216.11,
 216.13,
 216.28,
 216.46,
 216.53,
 216.56,
 216.66,
 216.71,
 216.92,
 217.34,
 217.4,
 217.59,
 217.82,
 217.9,
 218.0,
 218.06,
 218.33,
 218.45,
 218.61,
 218.74,
 218.82,
 218.87,
 219.12,
 219.17,
 219.32,
 219.36,
 219.53,
 219.58,
 219.7,
 219.71,
 219.87,
 219.92,
 220.01,
 220.03,
 220.2,
 220.25,
 221.08,
 221.24,
 221.28,
 221.29,
 221.29,
 221.3,
 221.76,
 221.82,
 221.9,
 221.94,
 222.08,
 222.18,
 222.22,
 222.23,
 222.25,
 222.4,
 222.42,
 222.42,
 222.6,
 222.87,
 223.14,
 223.2,
 223.39,
 223.63,
 223.78,
 223.89,
 224.16,
 224.35,
 224.5,
 224.55,
 224.78,
 224.87,
 224.9,
 224.95,
 225.16,
 225.26,
 225.34,
 225.39,
 225.47,
 225.6,
 225.88,
 226.12,
 226.25,
 226.28,
 226.64,
 226.74,
 226.9,
 227.08,
 227.13,
 227.15,
 227.29,
 227.33,
 227.56,
 227.59,
 227.65,
 227.87,
 228.05,
 228.05,
 228.08,
 228.28,
 228.32,
 228.5,
 228.53,
 228.54,
 228.55,
 228.77,
 228.85,
 228.87,
 228.92,
 229.04,
 229.06,
 229.08,
 229.19,
 229.32,
 229.57,
 229.61,
 229.77,
 229.94,
 229.97,
 230.01,
 230.05,
 230.23,
 230.42,
 230.5,
 230.5,
 230.6,
 230.66,
 230.68,
 230.71,
 230.71,
 230.78,
 230.79,
 230.91,
 231.05,
 231.17,
 231.22,
 231.27,
 231.36,
 231.41,
 231.58,
 231.58,
 231.75,
 231.8,
 231.86,
 231.86,
 231.97,
 231.97,
 232.03,
 232.14,
 232.23,
 232.27,
 232.39,
 232.39,
 232.6,
 232.62,
 232.62,
 232.66,
 232.73,
 232.8,
 232.86,
 232.89,
 232.91,
 233.02,
 233.14,
 233.17,
 233.22,
 233.32,
 233.35,
 233.4,
 233.46,
 233.51,
 233.52,
 233.56,
 233.67,
 233.7,
 233.75,
 233.77,
 233.78,
 233.87,
 234.06,
 234.08,
 234.13,
 234.17,
 234.27,
 234.3,
 234.39,
 234.65,
 234.72,
 234.74,
 234.77,
 234.91,
 234.92,
 235.05,
 235.06,
 235.07,
 235.23,
 235.24,
 235.27,
 235.28,
 235.31,
 235.32,
 235.35,
 235.45,
 235.45,
 235.5,
 235.52,
 235.58,
 235.59,
 235.66,
 235.79,
 235.8,
 235.81,
 235.83,
 236.05,
 236.06,
 236.07,
 236.08,
 236.1,
 236.16,
 236.19,
 236.38,
 236.42,
 236.54,
 236.64,
 236.65,
 236.75,
 236.77,
 236.84,
 236.9,
 236.93,
 237.2,
 237.26,
 237.27,
 237.31,
 237.32,
 237.36,
 237.46,
 237.5,
 237.57,
 237.68,
 237.69,
 237.69,
 237.69,
 237.77,
 237.83,
 237.85,
 237.96,
 238.05,
 238.17,
 238.24,
 238.3,
 238.32,
 238.32,
 238.34,
 238.51,
 238.53,
 238.53,
 238.76,
 239.26,
 239.27,
 239.29,
 239.3,
 239.32,
 239.69,
 239.87,
 239.91,
 ...]

In [6]:
list(pokemon)

['Bulbasaur',
 'Ivysaur',
 'Venusaur',
 'Charmander',
 'Charmeleon',
 'Charizard',
 'Squirtle',
 'Wartortle',
 'Blastoise',
 'Caterpie',
 'Metapod',
 'Butterfree',
 'Weedle',
 'Kakuna',
 'Beedrill',
 'Pidgey',
 'Pidgeotto',
 'Pidgeot',
 'Rattata',
 'Raticate',
 'Spearow',
 'Fearow',
 'Ekans',
 'Arbok',
 'Pikachu',
 'Raichu',
 'Sandshrew',
 'Sandslash',
 'Nidoran',
 'Nidorina',
 'Nidoqueen',
 'Nidoran♂',
 'Nidorino',
 'Nidoking',
 'Clefairy',
 'Clefable',
 'Vulpix',
 'Ninetales',
 'Jigglypuff',
 'Wigglytuff',
 'Zubat',
 'Golbat',
 'Oddish',
 'Gloom',
 'Vileplume',
 'Paras',
 'Parasect',
 'Venonat',
 'Venomoth',
 'Diglett',
 'Dugtrio',
 'Meowth',
 'Persian',
 'Psyduck',
 'Golduck',
 'Mankey',
 'Primeape',
 'Growlithe',
 'Arcanine',
 'Poliwag',
 'Poliwhirl',
 'Poliwrath',
 'Abra',
 'Kadabra',
 'Alakazam',
 'Machop',
 'Machoke',
 'Machamp',
 'Bellsprout',
 'Weepinbell',
 'Victreebel',
 'Tentacool',
 'Tentacruel',
 'Geodude',
 'Graveler',
 'Golem',
 'Ponyta',
 'Rapidash',
 'Slowpoke',
 'Slowbro',
 'Magnemite',
 'Magneton',
 "Farfetch'd",
 'Doduo',
 'Dodrio',
 'Seel',
 'Dewgong',
 'Grimer',
 'Muk',
 'Shellder',
 'Cloyster',
 'Gastly',
 'Haunter',
 'Gengar',
 'Onix',
 'Drowzee',
 'Hypno',
 'Krabby',
 'Kingler',
 'Voltorb',
 'Electrode',
 'Exeggcute',
 'Exeggutor',
 'Cubone',
 'Marowak',
 'Hitmonlee',
 'Hitmonchan',
 'Lickitung',
 'Koffing',
 'Weezing',
 'Rhyhorn',
 'Rhydon',
 'Chansey',
 'Tangela',
 'Kangaskhan',
 'Horsea',
 'Seadra',
 'Goldeen',
 'Seaking',
 'Staryu',
 'Starmie',
 'Mr. Mime',
 'Scyther',
 'Jynx',
 'Electabuzz',
 'Magmar',
 'Pinsir',
 'Tauros',
 'Magikarp',
 'Gyarados',
 'Lapras',
 'Ditto',
 'Eevee',
 'Vaporeon',
 'Jolteon',
 'Flareon',
 'Porygon',
 'Omanyte',
 'Omastar',
 'Kabuto',
 'Kabutops',
 'Aerodactyl',
 'Snorlax',
 'Articuno',
 'Zapdos',
 'Moltres',
 'Dratini',
 'Dragonair',
 'Dragonite',
 'Mewtwo',
 'Mew',
 'Chikorita',
 'Bayleef',
 'Meganium',
 'Cyndaquil',
 'Quilava',
 'Typhlosion',
 'Totodile',
 'Croconaw',
 'Feraligatr',
 'Sentret',
 'Furret',
 'Hoothoot',
 'Noctowl',
 'Ledyba',
 'Ledian',
 'Spinarak',
 'Ariados',
 'Crobat',
 'Chinchou',
 'Lanturn',
 'Pichu',
 'Cleffa',
 'Igglybuff',
 'Togepi',
 'Togetic',
 'Natu',
 'Xatu',
 'Mareep',
 'Flaaffy',
 'Ampharos',
 'Bellossom',
 'Marill',
 'Azumarill',
 'Sudowoodo',
 'Politoed',
 'Hoppip',
 'Skiploom',
 'Jumpluff',
 'Aipom',
 'Sunkern',
 'Sunflora',
 'Yanma',
 'Wooper',
 'Quagsire',
 'Espeon',
 'Umbreon',
 'Murkrow',
 'Slowking',
 'Misdreavus',
 'Unown',
 'Wobbuffet',
 'Girafarig',
 'Pineco',
 'Forretress',
 'Dunsparce',
 'Gligar',
 'Steelix',
 'Snubbull',
 'Granbull',
 'Qwilfish',
 'Scizor',
 'Shuckle',
 'Heracross',
 'Sneasel',
 'Teddiursa',
 'Ursaring',
 'Slugma',
 'Magcargo',
 'Swinub',
 'Piloswine',
 'Corsola',
 'Remoraid',
 'Octillery',
 'Delibird',
 'Mantine',
 'Skarmory',
 'Houndour',
 'Houndoom',
 'Kingdra',
 'Phanpy',
 'Donphan',
 'Porygon2',
 'Stantler',
 'Smeargle',
 'Tyrogue',
 'Hitmontop',
 'Smoochum',
 'Elekid',
 'Magby',
 'Miltank',
 'Blissey',
 'Raikou',
 'Entei',
 'Suicune',
 'Larvitar',
 'Pupitar',
 'Tyranitar',
 'Lugia',
 'Ho-oh',
 'Celebi',
 'Treecko',
 'Grovyle',
 'Sceptile',
 'Torchic',
 'Combusken',
 'Blaziken',
 'Mudkip',
 'Marshtomp',
 'Swampert',
 'Poochyena',
 'Mightyena',
 'Zigzagoon',
 'Linoone',
 'Wurmple',
 'Silcoon',
 'Beautifly',
 'Cascoon',
 'Dustox',
 'Lotad',
 'Lombre',
 'Ludicolo',
 'Seedot',
 'Nuzleaf',
 'Shiftry',
 'Taillow',
 'Swellow',
 'Wingull',
 'Pelipper',
 'Ralts',
 'Kirlia',
 'Gardevoir',
 'Surskit',
 'Masquerain',
 'Shroomish',
 'Breloom',
 'Slakoth',
 'Vigoroth',
 'Slaking',
 'Nincada',
 'Ninjask',
 'Shedinja',
 'Whismur',
 'Loudred',
 'Exploud',
 'Makuhita',
 'Hariyama',
 'Azurill',
 'Nosepass',
 'Skitty',
 'Delcatty',
 'Sableye',
 'Mawile',
 'Aron',
 'Lairon',
 'Aggron',
 'Meditite',
 'Medicham',
 'Electrike',
 'Manectric',
 'Plusle',
 'Minun',
 'Volbeat',
 'Illumise',
 'Roselia',
 'Gulpin',
 'Swalot',
 'Carvanha',
 'Sharpedo',
 'Wailmer',
 'Wailord',
 'Numel',
 'Camerupt',
 'Torkoal',
 'Spoink',
 'Grumpig',
 'Spinda',
 'Trapinch',
 'Vibrava',
 'Flygon',
 'Cacnea',
 'Cacturne',
 'Swablu',
 'Altaria',
 'Zangoose',
 'Seviper',
 'Lunatone',
 'Solrock',
 'Barboach',
 'Whiscash',
 'Corphish',
 'Crawdaunt',
 'Baltoy',
 'Claydol',
 'Lileep',
 'Cradily',
 'Anorith',
 'Armaldo',
 'Feebas',
 'Milotic',
 'Castform',
 'Kecleon',
 'Shuppet',
 'Banette',
 'Duskull',
 'Dusclops',
 'Tropius',
 'Chimecho',
 'Absol',
 'Wynaut',
 'Snorunt',
 'Glalie',
 'Spheal',
 'Sealeo',
 'Walrein',
 'Clamperl',
 'Huntail',
 'Gorebyss',
 'Relicanth',
 'Luvdisc',
 'Bagon',
 'Shelgon',
 'Salamence',
 'Beldum',
 'Metang',
 'Metagross',
 'Regirock',
 'Regice',
 'Registeel',
 'Latias',
 'Latios',
 'Kyogre',
 'Groudon',
 'Rayquaza',
 'Jirachi',
 'Deoxys',
 'Turtwig',
 'Grotle',
 'Torterra',
 'Chimchar',
 'Monferno',
 'Infernape',
 'Piplup',
 'Prinplup',
 'Empoleon',
 'Starly',
 'Staravia',
 'Staraptor',
 'Bidoof',
 'Bibarel',
 'Kricketot',
 'Kricketune',
 'Shinx',
 'Luxio',
 'Luxray',
 'Budew',
 'Roserade',
 'Cranidos',
 'Rampardos',
 'Shieldon',
 'Bastiodon',
 'Burmy',
 'Wormadam',
 'Mothim',
 'Combee',
 'Vespiquen',
 'Pachirisu',
 'Buizel',
 'Floatzel',
 'Cherubi',
 'Cherrim',
 'Shellos',
 'Gastrodon',
 'Ambipom',
 'Drifloon',
 'Drifblim',
 'Buneary',
 'Lopunny',
 'Mismagius',
 'Honchkrow',
 'Glameow',
 'Purugly',
 'Chingling',
 'Stunky',
 'Skuntank',
 'Bronzor',
 'Bronzong',
 'Bonsly',
 'Mime Jr.',
 'Happiny',
 'Chatot',
 'Spiritomb',
 'Gible',
 'Gabite',
 'Garchomp',
 'Munchlax',
 'Riolu',
 'Lucario',
 'Hippopotas',
 'Hippowdon',
 'Skorupi',
 'Drapion',
 'Croagunk',
 'Toxicroak',
 'Carnivine',
 'Finneon',
 'Lumineon',
 'Mantyke',
 'Snover',
 'Abomasnow',
 'Weavile',
 'Magnezone',
 'Lickilicky',
 'Rhyperior',
 'Tangrowth',
 'Electivire',
 'Magmortar',
 'Togekiss',
 'Yanmega',
 'Leafeon',
 'Glaceon',
 'Gliscor',
 'Mamoswine',
 'Porygon-Z',
 'Gallade',
 'Probopass',
 'Dusknoir',
 'Froslass',
 'Rotom',
 'Uxie',
 'Mesprit',
 'Azelf',
 'Dialga',
 'Palkia',
 'Heatran',
 'Regigigas',
 'Giratina',
 'Cresselia',
 'Phione',
 'Manaphy',
 'Darkrai',
 'Shaymin',
 'Arceus',
 'Victini',
 'Snivy',
 'Servine',
 'Serperior',
 'Tepig',
 'Pignite',
 'Emboar',
 'Oshawott',
 'Dewott',
 'Samurott',
 'Patrat',
 'Watchog',
 'Lillipup',
 'Herdier',
 'Stoutland',
 'Purrloin',
 'Liepard',
 'Pansage',
 'Simisage',
 'Pansear',
 'Simisear',
 'Panpour',
 'Simipour',
 'Munna',
 'Musharna',
 'Pidove',
 'Tranquill',
 'Unfezant',
 'Blitzle',
 'Zebstrika',
 'Roggenrola',
 'Boldore',
 'Gigalith',
 'Woobat',
 'Swoobat',
 'Drilbur',
 'Excadrill',
 'Audino',
 'Timburr',
 'Gurdurr',
 'Conkeldurr',
 'Tympole',
 'Palpitoad',
 'Seismitoad',
 'Throh',
 'Sawk',
 'Sewaddle',
 'Swadloon',
 'Leavanny',
 'Venipede',
 'Whirlipede',
 'Scolipede',
 'Cottonee',
 'Whimsicott',
 'Petilil',
 'Lilligant',
 'Basculin',
 'Sandile',
 'Krokorok',
 'Krookodile',
 'Darumaka',
 'Darmanitan',
 'Maractus',
 'Dwebble',
 'Crustle',
 'Scraggy',
 'Scrafty',
 'Sigilyph',
 'Yamask',
 'Cofagrigus',
 'Tirtouga',
 'Carracosta',
 'Archen',
 'Archeops',
 'Trubbish',
 'Garbodor',
 'Zorua',
 'Zoroark',
 'Minccino',
 'Cinccino',
 'Gothita',
 'Gothorita',
 'Gothitelle',
 'Solosis',
 'Duosion',
 'Reuniclus',
 'Ducklett',
 'Swanna',
 'Vanillite',
 'Vanillish',
 'Vanilluxe',
 'Deerling',
 'Sawsbuck',
 'Emolga',
 'Karrablast',
 'Escavalier',
 'Foongus',
 'Amoonguss',
 'Frillish',
 'Jellicent',
 'Alomomola',
 'Joltik',
 'Galvantula',
 'Ferroseed',
 'Ferrothorn',
 'Klink',
 'Klang',
 'Klinklang',
 'Tynamo',
 'Eelektrik',
 'Eelektross',
 'Elgyem',
 'Beheeyem',
 'Litwick',
 'Lampent',
 'Chandelure',
 'Axew',
 'Fraxure',
 'Haxorus',
 'Cubchoo',
 'Beartic',
 'Cryogonal',
 'Shelmet',
 'Accelgor',
 'Stunfisk',
 'Mienfoo',
 'Mienshao',
 'Druddigon',
 'Golett',
 'Golurk',
 'Pawniard',
 'Bisharp',
 'Bouffalant',
 'Rufflet',
 'Braviary',
 'Vullaby',
 'Mandibuzz',
 'Heatmor',
 'Durant',
 'Deino',
 'Zweilous',
 'Hydreigon',
 'Larvesta',
 'Volcarona',
 'Cobalion',
 'Terrakion',
 'Virizion',
 'Tornadus',
 'Thundurus',
 'Reshiram',
 'Zekrom',
 'Landorus',
 'Kyurem',
 'Keldeo',
 'Meloetta',
 'Genesect',
 'Chespin',
 'Quilladin',
 'Chesnaught',
 'Fennekin',
 'Braixen',
 'Delphox',
 'Froakie',
 'Frogadier',
 'Greninja',
 'Bunnelby',
 'Diggersby',
 'Fletchling',
 'Fletchinder',
 'Talonflame',
 'Scatterbug',
 'Spewpa',
 'Vivillon',
 'Litleo',
 'Pyroar',
 'Flabébé',
 'Floette',
 'Florges',
 'Skiddo',
 'Gogoat',
 'Pancham',
 'Pangoro',
 'Furfrou',
 'Espurr',
 'Meowstic',
 'Honedge',
 'Doublade',
 'Aegislash',
 'Spritzee',
 'Aromatisse',
 'Swirlix',
 'Slurpuff',
 'Inkay',
 'Malamar',
 'Binacle',
 'Barbaracle',
 'Skrelp',
 'Dragalge',
 'Clauncher',
 'Clawitzer',
 'Helioptile',
 'Heliolisk',
 'Tyrunt',
 'Tyrantrum',
 'Amaura',
 'Aurorus',
 'Sylveon',
 'Hawlucha',
 'Dedenne',
 'Carbink',
 'Goomy',
 'Sliggoo',
 'Goodra',
 'Klefki',
 'Phantump',
 'Trevenant',
 'Pumpkaboo',
 'Gourgeist',
 'Bergmite',
 'Avalugg',
 'Noibat',
 'Noivern',
 'Xerneas',
 'Yveltal',
 'Zygarde',
 'Diancie',
 'Hoopa',
 'Volcanion']

In [7]:
Poke_list=list(pokemon)

In [8]:
dict(google)

{0: np.float64(50.12),
 1: np.float64(54.1),
 2: np.float64(54.65),
 3: np.float64(52.38),
 4: np.float64(52.95),
 5: np.float64(53.9),
 6: np.float64(53.02),
 7: np.float64(50.95),
 8: np.float64(51.13),
 9: np.float64(50.07),
 10: np.float64(50.7),
 11: np.float64(49.95),
 12: np.float64(50.74),
 13: np.float64(51.1),
 14: np.float64(51.1),
 15: np.float64(52.61),
 16: np.float64(53.7),
 17: np.float64(55.69),
 18: np.float64(55.94),
 19: np.float64(56.93),
 20: np.float64(58.69),
 21: np.float64(59.62),
 22: np.float64(58.86),
 23: np.float64(59.13),
 24: np.float64(60.35),
 25: np.float64(59.86),
 26: np.float64(59.07),
 27: np.float64(63.37),
 28: np.float64(65.47),
 29: np.float64(64.74),
 30: np.float64(66.22),
 31: np.float64(67.46),
 32: np.float64(69.12),
 33: np.float64(68.47),
 34: np.float64(69.36),
 35: np.float64(68.8),
 36: np.float64(67.56),
 37: np.float64(68.63),
 38: np.float64(70.38),
 39: np.float64(70.93),
 40: np.float64(71.98),
 41: np.float64(74.51),
 42: np.float64(73.9),
 43: np.float64(70.17),
 44: np.float64(74.62),
 45: np.float64(86.13),
 46: np.float64(93.61),
 47: np.float64(90.81),
 48: np.float64(92.89),
 49: np.float64(96.55),
 50: np.float64(95.22),
 51: np.float64(97.92),
 52: np.float64(97.34),
 53: np.float64(95.74),
 54: np.float64(92.26),
 55: np.float64(84.59),
 56: np.float64(86.19),
 57: np.float64(84.27),
 58: np.float64(83.85),
 59: np.float64(91.42),
 60: np.float64(90.91),
 61: np.float64(92.34),
 62: np.float64(86.19),
 63: np.float64(86.16),
 64: np.float64(83.69),
 65: np.float64(84.62),
 66: np.float64(82.47),
 67: np.float64(83.68),
 68: np.float64(87.29),
 69: np.float64(89.61),
 70: np.float64(90.43),
 71: np.float64(90.9),
 72: np.float64(89.89),
 73: np.float64(89.61),
 74: np.float64(90.11),
 75: np.float64(88.06),
 76: np.float64(85.63),
 77: np.float64(84.91),
 78: np.float64(86.63),
 79: np.float64(85.74),
 80: np.float64(85.14),
 81: np.float64(89.26),
 82: np.float64(89.8),
 83: np.float64(88.15),
 84: np.float64(89.95),
 85: np.float64(92.42),
 86: np.float64(91.78),
 87: np.float64(93.06),
 88: np.float64(93.86),
 89: np.float64(95.86),
 90: np.float64(96.28),
 91: np.float64(96.35),
 92: np.float64(98.7),
 93: np.float64(96.3),
 94: np.float64(101.25),
 95: np.float64(97.15),
 96: np.float64(96.66),
 97: np.float64(94.18),
 98: np.float64(96.83),
 99: np.float64(97.43),
 100: np.float64(96.67),
 101: np.float64(97.59),
 102: np.float64(97.57),
 103: np.float64(99.89),
 104: np.float64(101.85),
 105: np.float64(98.55),
 106: np.float64(96.86),
 107: np.float64(94.05),
 108: np.float64(90.27),
 109: np.float64(88.47),
 110: np.float64(94.53),
 111: np.float64(93.95),
 112: np.float64(95.07),
 113: np.float64(97.71),
 114: np.float64(95.85),
 115: np.float64(102.88),
 116: np.float64(105.32),
 117: np.float64(102.08),
 118: np.float64(97.92),
 119: np.float64(99.22),
 120: np.float64(95.69),
 121: np.float64(93.9),
 122: np.float64(93.61),
 123: np.float64(96.4),
 124: np.float64(97.52),
 125: np.float64(99.11),
 126: np.float64(98.85),
 127: np.float64(98.88),
 128: np.float64(95.59),
 129: np.float64(96.88),
 130: np.float64(94.35),
 131: np.float64(92.84),
 132: np.float64(93.9),
 133: np.float64(92.94),
 134: np.float64(92.5),
 135: np.float64(93.41),
 136: np.float64(92.86),
 137: np.float64(94.31),
 138: np.float64(92.51),
 139: np.float64(90.58),
 140: np.float64(89.9),
 141: np.float64(88.81),
 142: np.float64(87.41),
 143: np.float64(89.22),
 144: np.float64(87.71),
 145: np.float64(89.56),
 146: np.float64(89.93),
 147: np.float64(90.35),
 148: np.float64(89.21),
 149: np.float64(89.4),
 150: np.float64(89.54),
 151: np.float64(90.62),
 152: np.float64(89.7),
 153: np.float64(90.13),
 154: np.float64(90.16),
 155: np.float64(89.93),
 156: np.float64(92.55),
 157: np.float64(94.19),
 158: np.float64(94.52),
 159: np.float64(96.78),
 160: np.float64(95.93),
 161: np.float64(96.52),
 162: np.float64(96.88),
 163: np.float64(96.37),
 164: np.float64(95.63),
 165: np.float64(92.41),
 166: np.float64(93.39),
 167: np.float64(95.6),
 168: np.float64(98.95),
 169: np.float64(102.01),
 170: np.float64(107.8),
 171: np.float64(111.65),
 172: np.float64(109.27),
 173: np.float64(109.78),
 174: np.float64(109.62),
 175: np.float64(109.89),
 176: np.float64(111.03),
 177: np.float64(112.98),
 178: np.float64(114.14),
 179: np.float64(113.38),
 180: np.float64(113.9),
 181: np.float64(112.9),
 182: np.float64(113.79),
 183: np.float64(115.53),
 184: np.float64(114.25),
 185: np.float64(114.51),
 186: np.float64(115.41),
 187: np.float64(116.45),
 188: np.float64(119.46),
 189: np.float64(119.47),
 190: np.float64(120.68),
 191: np.float64(127.6),
 192: np.float64(127.87),
 193: np.float64(130.27),
 194: np.float64(129.47),
 195: np.float64(132.87),
 196: np.float64(138.5),
 197: np.float64(143.86),
 198: np.float64(143.81),
 199: np.float64(139.99),
 200: np.float64(145.32),
 201: np.float64(146.41),
 202: np.float64(139.64),
 203: np.float64(143.01),
 204: np.float64(141.11),
 205: np.float64(141.23),
 206: np.float64(139.04),
 207: np.float64(137.26),
 208: np.float64(138.58),
 209: np.float64(140.0),
 210: np.float64(143.21),
 211: np.float64(143.78),
 212: np.float64(144.51),
 213: np.float64(144.71),
 214: np.float64(148.48),
 215: np.float64(151.9),
 216: np.float64(150.85),
 217: np.float64(146.21),
 218: np.float64(146.93),
 219: np.float64(145.48),
 220: np.float64(147.71),
 221: np.float64(145.62),
 222: np.float64(147.62),
 223: np.float64(147.97),
 224: np.float64(146.53),
 225: np.float64(145.75),
 226: np.float64(149.28),
 227: np.float64(150.29),
 228: np.float64(150.44),
 229: np.float64(149.62),
 230: np.float64(154.8),
 231: np.float64(155.84),
 232: np.float64(156.81),
 233: np.float64(151.05),
 234: np.float64(147.78),
 235: np.float64(147.9),
 236: np.float64(148.32),
 237: np.float64(146.6),
 238: np.float64(143.74),
 239: np.float64(145.66),
 240: np.float64(149.45),
 241: np.float64(148.5),
 242: np.float64(148.72),
 243: np.float64(146.03),
 244: np.float64(145.48),
 245: np.float64(145.64),
 246: np.float64(142.7),
 247: np.float64(141.88),
 248: np.float64(144.72),
 249: np.float64(141.86),
 250: np.float64(142.68),
 251: np.float64(142.41),
 252: np.float64(139.86),
 253: np.float64(139.86),
 254: np.float64(136.87),
 255: np.float64(139.65),
 256: np.float64(141.14),
 257: np.float64(141.15),
 258: np.float64(141.65),
 259: np.float64(144.08),
 260: np.float64(143.49),
 261: np.float64(142.86),
 262: np.float64(142.98),
 263: np.float64(144.08),
 264: np.float64(143.41),
 265: np.float64(147.29),
 266: np.float64(147.55),
 267: np.float64(149.4),
 268: np.float64(154.72),
 269: np.float64(155.68),
 270: np.float64(151.35),
 271: np.float64(151.16),
 272: np.float64(149.95),
 273: np.float64(151.74),
 274: np.float64(153.8),
 275: np.float64(155.79),
 276: np.float64(155.53),
 277: np.float64(157.52),
 278: np.float64(156.98),
 279: np.float64(156.81),
 280: np.float64(152.85),
 281: np.float64(154.66),
 282: np.float64(158.07),
 283: np.float64(159.18),
 284: np.float64(155.34),
 285: np.float64(155.2),
 286: np.float64(156.22),
 287: np.float64(156.34),
 288: np.float64(155.17),
 289: np.float64(152.9),
 290: np.float64(150.33),
 291: np.float64(148.57),
 292: np.float64(147.92),
 293: np.float64(152.35),
 294: np.float64(151.49),
 295: np.float64(154.2),
 296: np.float64(151.45),
 297: np.float64(169.78),
 298: np.float64(174.15),
 299: np.float64(173.28),
 300: np.float64(177.54),
 301: np.float64(176.35),
 302: np.float64(178.91),
 303: np.float64(185.88),
 304: np.float64(189.5),
 305: np.float64(189.65),
 306: np.float64(192.78),
 307: np.float64(195.02),
 308: np.float64(197.32),
 309: np.float64(194.76),
 310: np.float64(189.39),
 311: np.float64(195.35),
 312: np.float64(195.0),
 313: np.float64(198.29),
 314: np.float64(196.2),
 315: np.float64(198.88),
 316: np.float64(201.52),
 317: np.float64(199.9),
 318: np.float64(204.48),
 319: np.float64(208.03),
 320: np.float64(211.22),
 321: np.float64(214.1),
 322: np.float64(211.53),
 323: np.float64(201.57),
 324: np.float64(202.25),
 325: np.float64(206.84),
 326: np.float64(208.64),
 327: np.float64(202.72),
 328: np.float64(202.07),
 329: np.float64(201.91),
 330: np.float64(205.12),
 331: np.float64(204.4),
 332: np.float64(206.1),
 333: np.float64(208.54),
 334: np.float64(209.27),
 335: np.float64(211.05),
 336: np.float64(214.86),
 337: np.float64(212.09),
 338: np.float64(214.66),
 339: np.float64(212.95),
 340: np.float64(215.8),
 341: np.float64(215.25),
 342: np.float64(212.11),
 343: np.float64(213.13),
 344: np.float64(209.86),
 345: np.float64(207.22),
 346: np.float64(217.4),
 347: np.float64(222.4),
 348: np.float64(225.39),
 349: np.float64(232.6),
 350: np.float64(233.22),
 351: np.float64(234.65),
 352: np.float64(235.58),
 353: np.float64(231.58),
 354: np.float64(232.89),
 355: np.float64(233.32),
 356: np.float64(222.23),
 357: np.float64(218.0),
 358: np.float64(199.53),
 359: np.float64(213.54),
 360: np.float64(221.29),
 361: np.float64(216.28),
 362: np.float64(216.92),
 363: np.float64(216.53),
 364: np.float64(213.2),
 365: np.float64(216.11),
 366: np.float64(200.69),
 367: np.float64(197.82),
 368: np.float64(190.59),
 369: np.float64(192.36),
 370: np.float64(183.78),
 371: np.float64(184.36),
 372: np.float64(179.21),
 373: np.float64(181.12),
 374: np.float64(172.68),
 375: np.float64(171.49),
 376: np.float64(171.02),
 377: np.float64(183.05),
 378: np.float64(184.19),
 379: np.float64(183.11),
 380: np.float64(182.56),
 381: np.float64(188.85),
 382: np.float64(188.51),
 383: np.float64(194.99),
 384: np.float64(181.13),
 385: np.float64(182.22),
 386: np.float64(188.04),
 387: np.float64(188.9),
 388: np.float64(183.87),
 389: np.float64(182.04),
 390: np.float64(176.76),
 391: np.float64(171.33),
 392: np.float64(168.58),
 393: np.float64(168.36),
 394: np.float64(175.4),
 395: np.float64(172.08),
 396: np.float64(169.22),
 397: np.float64(169.73),
 398: np.float64(173.92),
 399: np.float64(169.79),
 400: np.float64(169.94),
 401: np.float64(170.77),
 402: np.float64(182.72),
 403: np.float64(184.66),
 404: np.float64(188.41),
 405: np.float64(197.29),
 406: np.float64(194.03),
 407: np.float64(194.8),
 408: np.float64(194.66),
 409: np.float64(201.97),
 410: np.float64(203.79),
 411: np.float64(205.38),
 412: np.float64(202.88),
 413: np.float64(207.98),
 414: np.float64(204.63),
 415: np.float64(204.27),
 416: np.float64(200.88),
 417: np.float64(203.21),
 418: np.float64(201.92),
 419: np.float64(205.04),
 420: np.float64(207.29),
 421: np.float64(218.33),
 422: np.float64(220.03),
 423: np.float64(213.37),
 424: np.float64(212.77),
 425: np.float64(209.8),
 426: np.float64(208.76),
 427: np.float64(199.25),
 428: np.float64(197.2),
 429: np.float64(196.89),
 430: np.float64(197.18),
 431: np.float64(196.95),
 432: np.float64(197.19),
 433: np.float64(204.2),
 434: np.float64(201.29),
 435: np.float64(193.31),
 436: np.float64(186.88),
 437: np.float64(187.91),
 438: np.float64(185.46),
 439: np.float64(187.06),
 440: np.float64(185.31),
 441: np.float64(184.82),
 442: np.float64(185.29),
 443: np.float64(187.6),
 444: np.float64(190.43),
 445: np.float64(191.3),
 446: np.float64(190.48),
 447: np.float64(185.78),
 448: np.float64(185.72),
 449: np.float64(191.12),
 450: np.float64(189.53),
 451: np.float64(187.03),
 452: np.float64(194.8),
 453: np.float64(193.06),
 454: np.float64(196.45),
 455: np.float64(193.09),
 456: np.float64(190.58),
 457: np.float64(193.07),
 458: np.float64(192.0),
 459: np.float64(195.3),
 460: np.float64(195.15),
 461: np.float64(193.88),
 462: np.float64(193.39),
 463: np.float64(200.86),
 464: np.float64(199.78),
 465: np.float64(202.23),
 466: np.float64(201.91),
 467: np.float64(200.96),
 468: np.float64(202.85),
 469: np.float64(208.7),
 470: np.float64(209.46),
 471: np.float64(211.39),
 472: np.float64(210.52),
 473: np.float64(211.38),
 474: np.float64(210.01),
 475: np.float64(208.89),
 476: np.float64(212.07),
 477: np.float64(208.42),
 478: np.float64(204.21),
 479: np.float64(201.55),
 480: np.float64(203.74),
 481: np.float64(201.32),
 482: np.float64(199.3),
 483: np.float64(193.37),
 484: np.float64(194.86),
 485: np.float64(195.25),
 486: np.float64(194.49),
 487: np.float64(192.56),
 488: np.float64(191.01),
 489: np.float64(193.87),
 490: np.float64(193.11),
 491: np.float64(187.57),
 492: np.float64(183.43),
 493: np.float64(187.51),
 494: np.float64(186.74),
 495: np.float64(188.79),
 496: np.float64(190.31),
 497: np.float64(188.28),
 498: np.float64(186.91),
 499: np.float64(184.07),
 500: np.float64(184.53),
 501: np.float64(190.29),
 502: np.float64(193.67),
 503: np.float64(192.71),
 504: np.float64(191.49),
 505: np.float64(188.46),
 506: np.float64(188.96),
 507: np.float64(186.53),
 508: np.float64(186.68),
 509: np.float64(186.44),
 510: np.float64(190.28),
 511: np.float64(189.29),
 512: np.float64(190.18),
 513: np.float64(189.08),
 514: np.float64(189.11),
 515: np.float64(191.99),
 516: np.float64(189.88),
 517: np.float64(189.06),
 518: np.float64(188.74),
 519: np.float64(191.85),
 520: np.float64(195.75),
 521: np.float64(203.08),
 522: np.float64(201.79),
 523: np.float64(204.74),
 524: np.float64(207.14),
 525: np.float64(201.7),
 526: np.float64(198.3),
 527: np.float64(203.22),
 528: np.float64(201.69),
 529: np.float64(201.79),
 530: np.float64(203.23),
 531: np.float64(201.26),
 532: np.float64(201.59),
 533: np.float64(200.75),
 534: np.float64(200.52),
 535: np.float64(201.82),
 536: np.float64(207.64),
 537: np.float64(205.7),
 538: np.float64(210.04),
 539: np.float64(214.29),
 540: np.float64(213.11),
 541: np.float64(213.04),
 542: np.float64(213.51),
 543: np.float64(213.44),
 544: np.float64(210.66),
 545: np.float64(210.11),
 546: np.float64(209.44),
 547: np.float64(212.82),
 548: np.float64(229.61),
 549: np.float64(240.15),
 550: np.float64(236.42),
 551: np.float64(243.06),
 552: np.float64(242.31),
 553: np.float64(237.36),
 554: np.float64(238.05),
 555: np.float64(237.96),
 556: np.float64(233.52),
 557: np.float64(234.72),
 558: np.float64(235.66),
 559: np.float64(238.24),
 560: np.float64(236.05),
 561: np.float64(237.26),
 562: np.float64(236.08),
 563: np.float64(236.54),
 564: np.float64(240.27),
 565: np.float64(244.41),
 566: np.float64(245.72),
 567: np.float64(247.7),
 568: np.float64(249.15),
 569: np.float64(247.28),
 570: np.float64(254.57),
 571: np.float64(253.75),
 572: np.float64(252.2),
 573: np.float64(242.13),
 574: np.float64(244.51),
 575: np.float64(242.08),
 576: np.float64(242.16),
 577: np.float64(240.16),
 578: np.float64(242.18),
 579: np.float64(243.26),
 580: np.float64(244.11),
 581: np.float64(241.08),
 582: np.float64(241.81),
 583: np.float64(241.72),
 584: np.float64(240.65),
 585: np.float64(239.26),
 586: np.float64(240.82),
 587: np.float64(239.91),
 588: np.float64(231.17),
 589: np.float64(234.08),
 590: np.float64(231.22),
 591: np.float64(227.87),
 592: np.float64(227.56),
 593: np.float64(228.54),
 594: np.float64(233.78),
 595: np.float64(231.05),
 596: np.float64(230.01),
 597: np.float64(233.56),
 598: np.float64(241.39),
 599: np.float64(243.35),
 600: np.float64(241.55),
 601: np.float64(242.51),
 602: np.float64(244.49),
 603: np.float64(249.61),
 604: np.float64(252.25),
 605: np.float64(251.89),
 606: np.float64(248.39),
 607: np.float64(243.67),
 608: np.float64(244.63),
 609: np.float64(240.18),
 610: np.float64(239.29),
 611: np.float64(249.28),
 612: np.float64(243.8),
 613: np.float64(247.67),
 614: np.float64(245.99),
 615: np.float64(246.91),
 616: np.float64(250.5),
 617: np.float64(240.63),
 618: np.float64(240.51),
 619: np.float64(233.35),
 620: np.float64(235.5),
 621: np.float64(234.77),
 622: np.float64(235.28),
 623: np.float64(230.71),
 624: np.float64(228.92),
 625: np.float64(229.32),
 626: np.float64(232.73),
 627: np.float64(230.5),
 628: np.float64(234.74),
 629: np.float64(235.81),
 630: np.float64(237.69),
 631: np.float64(237.69),
 632: np.float64(235.07),
 633: np.float64(232.23),
 634: np.float64(224.16),
 635: np.float64(224.5),
 636: np.float64(223.89),
 637: np.float64(219.12),
 638: np.float64(220.25),
 639: np.float64(228.55),
 640: np.float64(227.59),
 641: np.float64(227.13),
 642: np.float64(226.25),
 643: np.float64(227.15),
 644: np.float64(221.29),
 645: np.float64(223.78),
 646: np.float64(222.87),
 647: np.float64(220.2),
 648: np.float64(223.39),
 649: np.float64(222.42),
 650: np.float64(228.05),
 651: np.float64(230.79),
 652: np.float64(230.68),
 653: np.float64(232.27),
 654: np.float64(231.58),
 655: np.float64(230.71),
 656: np.float64(230.23),
 657: np.float64(228.85),
 658: np.float64(229.04),
 659: np.float64(236.06),
 660: np.float64(235.27),
 661: np.float64(235.52),
 662: np.float64(233.87),
 663: np.float64(233.02),
 664: np.float64(232.03),
 665: np.float64(233.46),
 666: np.float64(232.91),
 667: np.float64(236.9),
 668: np.float64(236.16),
 669: np.float64(237.77),
 670: np.float64(235.59),
 671: np.float64(241.0),
 672: np.float64(239.3),
 673: np.float64(238.53),
 674: np.float64(238.76),
 675: np.float64(240.35),
 676: np.float64(239.27),
 677: np.float64(235.45),
 678: np.float64(234.27),
 679: np.float64(232.66),
 680: np.float64(236.38),
 681: np.float64(235.32),
 682: np.float64(233.4),
 683: np.float64(233.17),
 684: np.float64(234.39),
 685: np.float64(230.5),
 686: np.float64(233.14),
 687: np.float64(230.66),
 688: np.float64(228.77),
 689: np.float64(236.07),
 690: np.float64(235.24),
 691: np.float64(234.92),
 692: np.float64(235.06),
 693: np.float64(237.69),
 694: np.float64(236.75),
 695: np.float64(236.93),
 696: np.float64(241.52),
 697: np.float64(243.31),
 698: np.float64(249.05),
 699: np.float64(248.71),
 700: np.float64(249.95),
 701: np.float64(253.28),
 702: np.float64(259.16),
 703: np.float64(258.87),
 704: np.float64(257.27),
 705: np.float64(257.49),
 706: np.float64(255.41),
 707: np.float64(252.13),
 708: np.float64(252.37),
 709: np.float64(251.17),
 710: np.float64(252.69),
 711: np.float64(257.34),
 712: np.float64(256.9),
 713: np.float64(254.73),
 714: np.float64(256.8),
 715: np.float64(262.23),
 716: np.float64(263.45),
 717: np.float64(264.86),
 718: np.float64(262.88),
 719: np.float64(262.24),
 720: np.float64(261.09),
 721: np.float64(264.92),
 722: np.float64(266.9),
 723: np.float64(270.54),
 724: np.float64(269.43),
 725: np.float64(271.01),
 726: np.float64(271.4),
 727: np.float64(271.96),
 728: np.float64(272.39),
 729: np.float64(275.8),
 730: np.float64(276.22),
 731: np.float64(277.22),
 732: np.float64(274.48),
 733: np.float64(274.02),
 734: np.float64(259.8),
 735: np.float64(256.0),
 736: np.float64(256.74),
 737: np.float64(254.63),
 738: np.float64(253.75),
 739: np.float64(255.69),
 740: np.float64(257.8),
 741: np.float64(254.74),
 742: np.float64(256.21),
 743: np.float64(255.25),
 744: np.float64(251.25),
 745: np.float64(254.74),
 746: np.float64(257.75),
 747: np.float64(262.63),
 748: np.float64(257.11),
 749: np.float64(257.62),
 750: np.float64(257.49),
 751: np.float64(254.05),
 752: np.float64(248.53),
 753: np.float64(245.51),
 754: np.float64(249.77),
 755: np.float64(248.71),
 756: np.float64(253.05),
 757: np.float64(256.12),
 758: np.float64(255.84),
 759: np.float64(257.24),
 760: np.float64(256.37),
 761: np.float64(252.95),
 762: np.float64(256.18),
 763: np.float64(255.44),
 764: np.float64(257.37),
 765: np.float64(262.31),
 766: np.float64(263.64),
 767: np.float64(261.5),
 768: np.float64(259.42),
 769: np.float64(256.98),
 770: np.float64(260.4),
 771: np.float64(261.06),
 772: np.float64(262.13),
 773: np.float64(264.11),
 774: np.float64(262.39),
 775: np.float64(267.37),
 776: np.float64(273.15),
 777: np.float64(276.14),
 778: np.float64(279.77),
 779: np.float64(283.73),
 780: np.float64(284.22),
 781: np.float64(283.8),
 782: np.float64(283.47),

In [9]:
max(pokemon)

'Zygarde'

In [10]:
min(pokemon)

'Abomasnow'

In [ ]:
max(google)

49.95

In [12]:
min(google)

49.95

# More Series attributes

In [13]:
pokemon.values

array(['Bulbasaur', 'Ivysaur', 'Venusaur', 'Charmander', 'Charmeleon',
       'Charizard', 'Squirtle', 'Wartortle', 'Blastoise', 'Caterpie',
       'Metapod', 'Butterfree', 'Weedle', 'Kakuna', 'Beedrill', 'Pidgey',
       'Pidgeotto', 'Pidgeot', 'Rattata', 'Raticate', 'Spearow', 'Fearow',
       'Ekans', 'Arbok', 'Pikachu', 'Raichu', 'Sandshrew', 'Sandslash',
       'Nidoran', 'Nidorina', 'Nidoqueen', 'Nidoran♂', 'Nidorino',
       'Nidoking', 'Clefairy', 'Clefable', 'Vulpix', 'Ninetales',
       'Jigglypuff', 'Wigglytuff', 'Zubat', 'Golbat', 'Oddish', 'Gloom',
       'Vileplume', 'Paras', 'Parasect', 'Venonat', 'Venomoth', 'Diglett',
       'Dugtrio', 'Meowth', 'Persian', 'Psyduck', 'Golduck', 'Mankey',
       'Primeape', 'Growlithe', 'Arcanine', 'Poliwag', 'Poliwhirl',
       'Poliwrath', 'Abra', 'Kadabra', 'Alakazam', 'Machop', 'Machoke',
       'Machamp', 'Bellsprout', 'Weepinbell', 'Victreebel', 'Tentacool',
       'Tentacruel', 'Geodude', 'Graveler', 'Golem', 'Ponyta', 'Rapidash',
       'Slowpoke', 'Slowbro', 'Magnemite', 'Magneton', "Farfetch'd",
       'Doduo', 'Dodrio', 'Seel', 'Dewgong', 'Grimer', 'Muk', 'Shellder',
       'Cloyster', 'Gastly', 'Haunter', 'Gengar', 'Onix', 'Drowzee',
       'Hypno', 'Krabby', 'Kingler', 'Voltorb', 'Electrode', 'Exeggcute',
       'Exeggutor', 'Cubone', 'Marowak', 'Hitmonlee', 'Hitmonchan',
       'Lickitung', 'Koffing', 'Weezing', 'Rhyhorn', 'Rhydon', 'Chansey',
       'Tangela', 'Kangaskhan', 'Horsea', 'Seadra', 'Goldeen', 'Seaking',
       'Staryu', 'Starmie', 'Mr. Mime', 'Scyther', 'Jynx', 'Electabuzz',
       'Magmar', 'Pinsir', 'Tauros', 'Magikarp', 'Gyarados', 'Lapras',
       'Ditto', 'Eevee', 'Vaporeon', 'Jolteon', 'Flareon', 'Porygon',
       'Omanyte', 'Omastar', 'Kabuto', 'Kabutops', 'Aerodactyl',
       'Snorlax', 'Articuno', 'Zapdos', 'Moltres', 'Dratini', 'Dragonair',
       'Dragonite', 'Mewtwo', 'Mew', 'Chikorita', 'Bayleef', 'Meganium',
       'Cyndaquil', 'Quilava', 'Typhlosion', 'Totodile', 'Croconaw',
       'Feraligatr', 'Sentret', 'Furret', 'Hoothoot', 'Noctowl', 'Ledyba',
       'Ledian', 'Spinarak', 'Ariados', 'Crobat', 'Chinchou', 'Lanturn',
       'Pichu', 'Cleffa', 'Igglybuff', 'Togepi', 'Togetic', 'Natu',
       'Xatu', 'Mareep', 'Flaaffy', 'Ampharos', 'Bellossom', 'Marill',
       'Azumarill', 'Sudowoodo', 'Politoed', 'Hoppip', 'Skiploom',
       'Jumpluff', 'Aipom', 'Sunkern', 'Sunflora', 'Yanma', 'Wooper',
       'Quagsire', 'Espeon', 'Umbreon', 'Murkrow', 'Slowking',
       'Misdreavus', 'Unown', 'Wobbuffet', 'Girafarig', 'Pineco',
       'Forretress', 'Dunsparce', 'Gligar', 'Steelix', 'Snubbull',
       'Granbull', 'Qwilfish', 'Scizor', 'Shuckle', 'Heracross',
       'Sneasel', 'Teddiursa', 'Ursaring', 'Slugma', 'Magcargo', 'Swinub',
       'Piloswine', 'Corsola', 'Remoraid', 'Octillery', 'Delibird',
       'Mantine', 'Skarmory', 'Houndour', 'Houndoom', 'Kingdra', 'Phanpy',
       'Donphan', 'Porygon2', 'Stantler', 'Smeargle', 'Tyrogue',
       'Hitmontop', 'Smoochum', 'Elekid', 'Magby', 'Miltank', 'Blissey',
       'Raikou', 'Entei', 'Suicune', 'Larvitar', 'Pupitar', 'Tyranitar',
       'Lugia', 'Ho-oh', 'Celebi', 'Treecko', 'Grovyle', 'Sceptile',
       'Torchic', 'Combusken', 'Blaziken', 'Mudkip', 'Marshtomp',
       'Swampert', 'Poochyena', 'Mightyena', 'Zigzagoon', 'Linoone',
       'Wurmple', 'Silcoon', 'Beautifly', 'Cascoon', 'Dustox', 'Lotad',
       'Lombre', 'Ludicolo', 'Seedot', 'Nuzleaf', 'Shiftry', 'Taillow',
       'Swellow', 'Wingull', 'Pelipper', 'Ralts', 'Kirlia', 'Gardevoir',
       'Surskit', 'Masquerain', 'Shroomish', 'Breloom', 'Slakoth',
       'Vigoroth', 'Slaking', 'Nincada', 'Ninjask', 'Shedinja', 'Whismur',
       'Loudred', 'Exploud', 'Makuhita', 'Hariyama', 'Azurill',
       'Nosepass', 'Skitty', 'Delcatty', 'Sableye', 'Mawile', 'Aron',
       'Lairon', 'Aggron', 'Meditite', 'Medicham', 'Electrike',
       'Manectric', 'Plusle', 'Minun', 'Volbeat', 'Illumise', 'Roselia',
       'Gulpin', 'Swalot', 'Carvanha', 'Sharpedo', 'Wailmer', 'Wailord',
       'Numel', 'Camerupt', 'Torkoal', 'Spoink', 'Grumpig', 'Spinda',
       'Trapinch', 'Vibrava', 'Flygon', 'Cacnea', 'Cacturne', 'Swablu',
       'Altaria', 'Zangoose', 'Seviper', 'Lunatone', 'Solrock',
       'Barboach', 'Whiscash', 'Corphish', 'Crawdaunt', 'Baltoy',
       'Claydol', 'Lileep', 'Cradily', 'Anorith', 'Armaldo', 'Feebas',
       'Milotic', 'Castform', 'Kecleon', 'Shuppet', 'Banette', 'Duskull',
       'Dusclops', 'Tropius', 'Chimecho', 'Absol', 'Wynaut', 'Snorunt',
       'Glalie', 'Spheal', 'Sealeo', 'Walrein', 'Clamperl', 'Huntail',
       'Gorebyss', 'Relicanth', 'Luvdisc', 'Bagon', 'Shelgon',
       'Salamence', 'Beldum', 'Metang', 'Metagross', 'Regirock', 'Regice',
       'Registeel', 'Latias', 'Latios', 'Kyogre', 'Groudon', 'Rayquaza',
       'Jirachi', 'Deoxys', 'Turtwig', 'Grotle', 'Torterra', 'Chimchar',
       'Monferno', 'Infernape', 'Piplup', 'Prinplup', 'Empoleon',
       'Starly', 'Staravia', 'Staraptor', 'Bidoof', 'Bibarel',
       'Kricketot', 'Kricketune', 'Shinx', 'Luxio', 'Luxray', 'Budew',
       'Roserade', 'Cranidos', 'Rampardos', 'Shieldon', 'Bastiodon',
       'Burmy', 'Wormadam', 'Mothim', 'Combee', 'Vespiquen', 'Pachirisu',
       'Buizel', 'Floatzel', 'Cherubi', 'Cherrim', 'Shellos', 'Gastrodon',
       'Ambipom', 'Drifloon', 'Drifblim', 'Buneary', 'Lopunny',
       'Mismagius', 'Honchkrow', 'Glameow', 'Purugly', 'Chingling',
       'Stunky', 'Skuntank', 'Bronzor', 'Bronzong', 'Bonsly', 'Mime Jr.',
       'Happiny', 'Chatot', 'Spiritomb', 'Gible', 'Gabite', 'Garchomp',
       'Munchlax', 'Riolu', 'Lucario', 'Hippopotas', 'Hippowdon',
       'Skorupi', 'Drapion', 'Croagunk', 'Toxicroak', 'Carnivine',
       'Finneon', 'Lumineon', 'Mantyke', 'Snover', 'Abomasnow', 'Weavile',
       'Magnezone', 'Lickilicky', 'Rhyperior', 'Tangrowth', 'Electivire',
       'Magmortar', 'Togekiss', 'Yanmega', 'Leafeon', 'Glaceon',
       'Gliscor', 'Mamoswine', 'Porygon-Z', 'Gallade', 'Probopass',
       'Dusknoir', 'Froslass', 'Rotom', 'Uxie', 'Mesprit', 'Azelf',
       'Dialga', 'Palkia', 'Heatran', 'Regigigas', 'Giratina',
       'Cresselia', 'Phione', 'Manaphy', 'Darkrai', 'Shaymin', 'Arceus',
       'Victini', 'Snivy', 'Servine', 'Serperior', 'Tepig', 'Pignite',
       'Emboar', 'Oshawott', 'Dewott', 'Samurott', 'Patrat', 'Watchog',
       'Lillipup', 'Herdier', 'Stoutland', 'Purrloin', 'Liepard',
       'Pansage', 'Simisage', 'Pansear', 'Simisear', 'Panpour',
       'Simipour', 'Munna', 'Musharna', 'Pidove', 'Tranquill', 'Unfezant',
       'Blitzle', 'Zebstrika', 'Roggenrola', 'Boldore', 'Gigalith',
       'Woobat', 'Swoobat', 'Drilbur', 'Excadrill', 'Audino', 'Timburr',
       'Gurdurr', 'Conkeldurr', 'Tympole', 'Palpitoad', 'Seismitoad',
       'Throh', 'Sawk', 'Sewaddle', 'Swadloon', 'Leavanny', 'Venipede',
       'Whirlipede', 'Scolipede', 'Cottonee', 'Whimsicott', 'Petilil',
       'Lilligant', 'Basculin', 'Sandile', 'Krokorok', 'Krookodile',
       'Darumaka', 'Darmanitan', 'Maractus', 'Dwebble', 'Crustle',
       'Scraggy', 'Scrafty', 'Sigilyph', 'Yamask', 'Cofagrigus',
       'Tirtouga', 'Carracosta', 'Archen', 'Archeops', 'Trubbish',
       'Garbodor', 'Zorua', 'Zoroark', 'Minccino', 'Cinccino', 'Gothita',
       'Gothorita', 'Gothitelle', 'Solosis', 'Duosion', 'Reuniclus',
       'Ducklett', 'Swanna', 'Vanillite', 'Vanillish', 'Vanilluxe',
       'Deerling', 'Sawsbuck', 'Emolga', 'Karrablast', 'Escavalier',
       'Foongus', 'Amoonguss', 'Frillish', 'Jellicent', 'Alomomola',
       'Joltik', 'Galvantula', 'Ferroseed', 'Ferrothorn', 'Klink',
       'Klang', 'Klinklang', 'Tynamo', 'Eelektrik', 'Eelektross',
       'Elgyem', 'Beheeyem', 'Litwick', 'Lampent', 'Chandelure', 'Axew',
       'Fraxure', 'Haxorus', 'Cubchoo', 'Beartic', 'Cryogonal', 'Shelmet',
       'Accelgor', 'Stunfisk', 'Mienfoo', 'Mienshao', 'Druddigon',
       'Golett', 'Golurk', 'Pawniard', 'Bisharp', 'Bouffalant', 'Rufflet',
       'Braviary', 'Vullaby', 'Mandibuzz', 'Heatmor', 'Durant', 'Deino',
       'Zweilous', 'Hydreigon', 'Larvesta', 'Volcarona', 'Cobalion',
       'Terrakion', 'Virizion', 'Tornadus', 'Thundurus', 'Reshiram',
       'Zekrom', 'Landorus', 'Kyurem', 'Keldeo', 'Meloetta', 'Genesect',
       'Chespin', 'Quilladin', 'Chesnaught', 'Fennekin', 'Braixen',
       'Delphox', 'Froakie', 'Frogadier', 'Greninja', 'Bunnelby',
       'Diggersby', 'Fletchling', 'Fletchinder', 'Talonflame',
       'Scatterbug', 'Spewpa', 'Vivillon', 'Litleo', 'Pyroar', 'Flabébé',
       'Floette', 'Florges', 'Skiddo', 'Gogoat', 'Pancham', 'Pangoro',
       'Furfrou', 'Espurr', 'Meowstic', 'Honedge', 'Doublade',
       'Aegislash', 'Spritzee', 'Aromatisse', 'Swirlix', 'Slurpuff',
       'Inkay', 'Malamar', 'Binacle', 'Barbaracle', 'Skrelp', 'Dragalge',
       'Clauncher', 'Clawitzer', 'Helioptile', 'Heliolisk', 'Tyrunt',
       'Tyrantrum', 'Amaura', 'Aurorus', 'Sylveon', 'Hawlucha', 'Dedenne',
       'Carbink', 'Goomy', 'Sliggoo', 'Goodra', 'Klefki', 'Phantump',
       'Trevenant', 'Pumpkaboo', 'Gourgeist', 'Bergmite', 'Avalugg',
       'Noibat', 'Noivern', 'Xerneas', 'Yveltal', 'Zygarde', 'Diancie',
       'Hoopa', 'Volcanion'], dtype=object)

In [15]:
google.values

array([ 50.12,  54.1 ,  54.65, ..., 773.18, 771.61, 782.22], shape=(3012,))

In [17]:
pokemon.index

RangeIndex(start=0, stop=721, step=1)

In [18]:
pokemon.is_unique

True

In [19]:
pokemon.ndim

1

In [21]:
pokemon.shape

(721,)

In [23]:
google.shape

(3012,)

In [24]:
google.is_unique

False

In [25]:
pokemon.name

'Pokemon'

# .sort_values() Method

In [27]:
pokemon.sort_values(ascending=False)

717      Zygarde
633     Zweilous
40         Zubat
569        Zorua
570      Zoroark
         ...
680    Aegislash
616     Accelgor
358        Absol
62          Abra
459    Abomasnow
Name: Pokemon, Length: 721, dtype: object

In [29]:
pokemon.sort_values().head()

459    Abomasnow
62          Abra
358        Absol
616     Accelgor
680    Aegislash
Name: Pokemon, dtype: object

In [ ]:
google.sort_values(ascending=True, inplace=True)

ValueError: This Series is a view of some other array, to sort in-place you must create a copy

In [32]:
google.head(3)

0    50.12
1    54.10
2    54.65
Name: Stock Price, dtype: float64

# .sort_index() Method

In [35]:
A=pokemon.sort_index(ascending=False)

In [36]:
A.head()

720    Volcanion
719        Hoopa
718      Diancie
717      Zygarde
716      Yveltal
Name: Pokemon, dtype: object

# Python's in Keyword

In [37]:
3 in [1,2,3]

True

In [46]:
if "Volcanion" in pokemon.values:
    print("Se encuentra")
else:
    print("No se encuentra")

Se encuentra

In [ ]:
100 in pokemon.index

False

In [47]:
"Digimon" in pokemon.values

False

# Extracting values by index Position

In [48]:
pokemon.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Pokemon, dtype: object

In [50]:
pokemon.values[-1]

'Volcanion'

In [53]:
pokemon[-1::]

720    Volcanion
Name: Pokemon, dtype: object

In [54]:
pokemon[2:3]

2    Venusaur
Name: Pokemon, dtype: object

In [55]:
pokemon[1:10]

1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
5     Charizard
6      Squirtle
7     Wartortle
8     Blastoise
9      Caterpie
Name: Pokemon, dtype: object

In [56]:
pokemon[:50]

0      Bulbasaur
1        Ivysaur
2       Venusaur
3     Charmander
4     Charmeleon
5      Charizard
6       Squirtle
7      Wartortle
8      Blastoise
9       Caterpie
10       Metapod
11    Butterfree
12        Weedle
13        Kakuna
14      Beedrill
15        Pidgey
16     Pidgeotto
17       Pidgeot
18       Rattata
19      Raticate
20       Spearow
21        Fearow
22         Ekans
23         Arbok
24       Pikachu
25        Raichu
26     Sandshrew
27     Sandslash
28       Nidoran
29      Nidorina
30     Nidoqueen
31      Nidoran♂
32      Nidorino
33      Nidoking
34      Clefairy
35      Clefable
36        Vulpix
37     Ninetales
38    Jigglypuff
39    Wigglytuff
40         Zubat
41        Golbat
42        Oddish
43         Gloom
44     Vileplume
45         Paras
46      Parasect
47       Venonat
48      Venomoth
49       Diglett
Name: Pokemon, dtype: object

# Extract Values by index Label

In [63]:
pd.read_csv("Datasets/pokemon.csv", index_col="Pokemon").squeeze(axis=1)

Pokemon
Bulbasaur       Grass
Ivysaur         Grass
Venusaur        Grass
Charmander       Fire
Charmeleon       Fire
               ...
Yveltal          Dark
Zygarde        Dragon
Diancie          Rock
Hoopa         Psychic
Volcanion        Fire
Name: Type, Length: 721, dtype: object

In [59]:
pokemon[0]

'Bulbasaur'

In [64]:
pokemon["Bulbasaur"]

KeyError: 'Bulbasaur'

In [66]:
pokemon[["Charizard", "Jolteon"]]

KeyError: "None of [Index(['Charizard', 'Jolteon'], dtype='object')] are in the [index]"

In [67]:
pokemon["Charmander" : "Weedle"]

TypeError: cannot do slice indexing on RangeIndex with these indexers [Charmander] of type str

In [ ]:
pokemon.reindex()

# .get() Method on a series

In [68]:
pokemon.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Pokemon, dtype: object

In [70]:
pokemon.get(0)

'Bulbasaur'

In [71]:
pokemon.get([0,5,100])

0      Bulbasaur
5      Charizard
100    Electrode
Name: Pokemon, dtype: object

In [73]:
valor=input("Type a pokemon")
pokemon.get(key=valor, default="This is not a pokemon")

'This is not a pokemon'

# Math Methods on a series object

In [30]:
google=pd.read_csv("Datasets/google_stock_price.csv")

In [4]:
google.count()

Stock Price    3012
dtype: int64

In [7]:
google.mean()

Stock Price    334.310093
dtype: float64

In [8]:
google.mode()

   Stock Price
0       291.21

In [9]:
google.describe()

       Stock Price
count  3012.000000
mean    334.310093
std     173.187205
min      49.950000
25%     218.045000
50%     283.315000
75%     443.000000
max     782.220000

# .idxmax() and idxmin() Methods

In [10]:
google.max()

Stock Price    782.22
dtype: float64

In [12]:
google.min()

Stock Price    49.95
dtype: float64

In [14]:
google.idxmax()

Stock Price    3011
dtype: int64

In [15]:
google.idxmin()

Stock Price    11
dtype: int64

In [16]:
google[3011]

KeyError: 3011

In [17]:
google[google.idxmin()]

KeyError: "None of [Index([11], dtype='int64')] are in the [columns]"

In [19]:
pokemon=pd.read_csv("Datasets/pokemon.csv")

In [21]:
pokemon.value_counts()

Pokemon    Type
Abomasnow  Grass     1
Ponyta     Fire      1
Porygon    Normal    1
Porygon-Z  Normal    1
Porygon2   Normal    1
                    ..
Golurk     Ground    1
Goodra     Dragon    1
Goomy      Dragon    1
Gorebyss   Water     1
Zygarde    Dragon    1
Name: count, Length: 721, dtype: int64

In [22]:
pokemon.value_counts().sum()

np.int64(721)

# .apply Method

In [29]:
def classify_performance(num):
    if num<300:
        return "ok"
    elif num>=300 and num <650:
        return "Satisfactory"
    else:
        return "Incredible"

In [36]:
google.apply(classify_performance)

0               ok
1               ok
2               ok
3               ok
4               ok
           ...
3007    Incredible
3008    Incredible
3009    Incredible
3010    Incredible
3011    Incredible
Name: Stock Price, Length: 3012, dtype: object

In [37]:
google=pd.read_csv("Datasets/google_stock_price.csv").squeeze()

In [39]:
google.apply(classify_performance).head()

0    ok
1    ok
2    ok
3    ok
4    ok
Name: Stock Price, dtype: object

In [41]:
google.apply(lambda stock_price : stock_price+1)

0        51.12
1        55.10
2        55.65
3        53.38
4        53.95
         ...
3007    773.88
3008    772.07
3009    774.18
3010    772.61
3011    783.22
Name: Stock Price, Length: 3012, dtype: float64

# The .map() Method

In [48]:
pokemon_names=pd.read_csv("Datasets/pokemon.csv", usecols=["Pokemon"]).squeeze()

In [49]:
pokemon_names.head()

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
Name: Pokemon, dtype: object

In [47]:
pokemon_types=pd.read_csv("Datasets/pokemon.csv", index_col="Pokemon").squeeze()

In [50]:
pokemon_types.head()

Pokemon
Bulbasaur     Grass
Ivysaur       Grass
Venusaur      Grass
Charmander     Fire
Charmeleon     Fire
Name: Type, dtype: object

In [52]:
pokemon_names.map(pokemon_types)

0        Grass
1        Grass
2        Grass
3         Fire
4         Fire
        ...
716       Dark
717     Dragon
718       Rock
719    Psychic
720       Fire
Name: Pokemon, Length: 721, dtype: object